### ISSUE TITLE
Fix CSV version numbering in operator-framework/community-operators

### ISSUE THREAD

**Issue by ron1** [mongodb/mongodb-enterprise-kubernetes#10]
mongodb-enterprise-operator has CSV v0.3.2 here https://github.com/operator-framework/community-operators/blob/1d1fde5d0bd0f82d6524a363ab6e535381b5d313/certified-operators/mongodb/mongodb-enterprise.v0.3.2.clusterserviceversion.yaml#L6 yet the version tags for the images being used in the CSV are unspecified. It would be more clear if the versions of the images were explicitly defined and those versions were consistent with the CSV version.

**Comment by rodrigovalin** [comment]
Hello @ron1, the process of updating these CSV files is not straightforward yet. Everything will be improved in the coming months. In the meantime I realized it is best for users to use the latest images available for OpenShift, unless they are not compatible with the existing CSV file, in which case the CSV file will be updated.
