### ISSUE TITLE
MongoDB without Ops Manager

### ISSUE THREAD

**Issue by stephan2012** [mongodb/mongodb-enterprise-kubernetes#100]
Is it possible to deploy a MongoDB replicaset in Kubernetes with the Enterprise Kubernetes Operator _without_ having to go for Ops Manager? I just need a small instance to run Graylog and deploying a [15 gig app](https://docs.opsmanager.mongodb.com/current/core/requirements/) seems to be overkill. We do not have any need for MongoDB in production for any other reasons at the moment.

**Comment by theburi** [comment]
Hi. For smaller deployments, you could use Cloud Manager.
Our current Enterprise solution relies on Ops Manager automation and monitoring to operate MongoDB clusters.
Another alternative will be open-source Community operators. There are a few available. 
There are Helm charts that could deploy simple replica sets.

We are currently working on OpenSource Operator. But it is a bit early days for that project.

**Comment by stephan2012** [comment]
Thanks for the pointers. I’m going to check them.

Looking forward to read about your Open Source Operator when it has arrived.
