### ISSUE TITLE
Can't create a MongoDB resource on an offline OpenShift 3.11

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#101]
My organization has an isolated offline network, and we are using mongodb operator v1.5.2 with cluster wide configuration. For some reason when I'm creating a MongoDB resource my operator throws an error in it's pod's logs:

```
Error updating status to Reconciling: the server rejected our request due to an error in our request
stacktrace: github.com/10gen/ops-manager-kubernetes/pkg/controller/operator. (*ReconcileCommonController) ....
```

What ca i do in this situation?

**Comment by LouisPlisso** [comment]
@ItayZviCohen thanks for reporting: we have a fix ready and it should be released soon

**Comment by ItayZviCohen** [comment]
Could you please comment on this issue when the fix has been released?

**Comment by LouisPlisso** [comment]
@ItayZviCohen can you please try the image in https://quay.io/repository/mongodb/mongodb-enterprise-operator-ubi-prerelease?tab=tags

Please try with 5ebaa406562343723be6291c

`image: quay.io/mongodb/mongodb-enterprise-operator-ubi-prerelease:5eba7a733e8e867cc29b748a`

We are going to release next week latest

**Comment by ItayZviCohen** [comment]
Just deployed the new image and the problem persists. Any leads?

**Comment by LouisPlisso** [comment]
@ItayZviCohen can you please provide the log messages
are you using operator 1.5.3?

**Comment by ItayZviCohen** [comment]
Yes I am using operator 1.5.3

Because we are using an isolated network, I can only send an image of the log message we are getting:
![WhatsApp Image 2020-06-04 at 09 29 47](https://user-images.githubusercontent.com/47146012/83722804-4b54ed80-a646-11ea-8221-8c837f89391d.jpeg)

**Comment by ItayZviCohen** [comment]
@LouisPlisso  any updates?

**Comment by ItayZviCohen** [comment]
Posting the "oc describe" of the operator's deployment if that helps:
![WhatsApp Image 2020-06-15 at 15 09 45](https://user-images.githubusercontent.com/47146012/84656165-ed17ec80-af1a-11ea-906d-0e1f2baebf67.jpeg)

**Comment by karl-denby** [comment]
Hi Itay, 
Lets continue this discussion in your support case: 00658530. 

You can attach multiple images directly to that case.

Karl

**Comment by ItayZviCohen** [comment]
Was resolved by MongoDB support. Thank you.
