### ISSUE TITLE
how to watch all namespaces?

### ISSUE THREAD

**Issue by toonsevrin** [mongodb/mongodb-enterprise-kubernetes#102]
Currently the operator only watches the namespace it is deployed in, is it possible to let it watch all namespaces?

**Comment by chatton** [comment]
Hi @toonsevrin 

You can configure the operator to watch all namespaces by providing a wildcard value as the namespace

```
env:
   - name: WATCH_NAMESPACE
     value: "*"
```

This will require an additional cluster role. See [the full process in the docs](https://docs.mongodb.com/kubernetes-operator/master/tutorial/install-k8s-operator/)

**Comment by toonsevrin** [comment]
Thank you very much!
