### ISSUE TITLE
adding tolerations to pods

### ISSUE THREAD

**Issue by brechtvalcke** [mongodb/mongodb-enterprise-kubernetes#106]
Hello, we are changing our cluster structure a bit.

One big change is the using of taints to make sure some nodes are reserved for essential applications like databases only. However I can't seem to add tolerations to my pods.

You guys support nodeAffinity, podAntiAffinity, thats good but tolerations is not one of them it seems. Is there a workaround?

**Comment by antonlisovenko** [comment]
Hi @brechtvalcke 

Thanks for your question.
I guess you are speaking about `MongoDB` CRD, not `MongoDBOpsManager`?
We allow flexible configuration of pod configuration using `podSpec.podTemplate`: https://docs.mongodb.com/kubernetes-operator/stable/reference/k8s-operator-specification/#spec.podSpec.podTemplate

you can find more examples [here](https://github.com/mongodb/mongodb-enterprise-kubernetes/tree/master/samples/mongodb/pod-template)

**Comment by brechtvalcke** [comment]
Hey @antonlisovenko,

Thank you, indeed I was talking about the CRD's. Did not realize that I can add any configuration I want to the pod this way. I noticed that it was not in the list, so I assumed it was not possible (source: [Replicaset documentation](https://docs.mongodb.com/kubernetes-operator/stable/tutorial/deploy-replica-set/#add-any-additional-accepted-settings-for-a-replica-set-deployment)).

I will try it out and report back. The documentation in my source clearly communicates you can only add the properties listed there. So if it is true it might be good to update that for future users.

**Comment by antonlisovenko** [comment]
yes @brechtvalcke  our documentation lacked the reference for `podTemplate` - we've already filed the relevant ticket. Thanks for pointing to this!

**Comment by brechtvalcke** [comment]
Yes great, very clear in the documentation you sent over. It worked without any hassle. Thank you for the quick reply and solution! I'll close this one as I have my solution.
