### ISSUE TITLE
Can you connect to mongo inside k8 cluster via the Service(ClusterIP) rather than targeting each pod? It seems cleaner that way than having multiple pod(dns) in replicaset and sharded cluster.

### ISSUE THREAD

**Issue by g3gurung** [mongodb/mongodb-enterprise-kubernetes#107]
![Screenshot 2020-06-11 at 10 25 06](https://user-images.githubusercontent.com/6603227/84357267-0db80d80-abce-11ea-9c8f-0a51ef7d8cb6.png)
![Screenshot 2020-06-11 at 10 27 50](https://user-images.githubusercontent.com/6603227/84357389-39d38e80-abce-11ea-86da-6eb9757ed823.png)

Do I need to expose the all the **replicaset pods** and then put them in connection string or just **my-service** is enough for connection?

**Comment by antonlisovenko** [comment]
hi @g3gurung 

Thanks for you question

The format of the connection url to the replica set is described in more details here: https://docs.mongodb.com/manual/reference/connection-string/
In a nutshell:
* It's highly recommended to list all the replica hosts in the connection url. MongoDB drivers rely on this format internally. This means that just putting the `ClusterIP` service name that resolves to all pod IPs is not enough.
* There is a way to use the service name instead of listing the pods though - this can be achieved by using the special form of connection url `mongodb+srv://`

The example:

I have a `my-replica-set` MongoDB resource:
```
$ kubectl get mdb
NAME             TYPE         STATE     VERSION   AGE
my-replica-set   ReplicaSet   Running   3.6.9     15m
```

Now I can connect to it just using the service name:
```
# execute into the container
$ kubectl exec -it my-replica-set-0 bash
groups: cannot find name for group ID 2000
# connect to the replica set
I have no name!@my-replica-set-0:/$  /var/lib/mongodb-mms-automation/mongodb-linux-x86_64-3.6.9/bin/mongo "mongodb+srv://my-replica-set-svc.cloudqa.svc.cluster.local/?ssl=false"
MongoDB shell version v3.6.9
connecting to: mongodb+srv://my-replica-set-svc.cloudqa.svc.cluster.local/?ssl=false
Implicit session: session { "id" : UUID("29bd0e80-840e-4896-ae49-89f83b06b693") }
MongoDB server version: 3.6.9
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
2020-06-11T09:41:29.434+0000 I STORAGE  [main] In File::open(), ::open for '//.mongorc.js' failed with Permission denied
Server has startup warnings:
2020-06-11T09:04:32.079+0000 I CONTROL  [initandlisten]
2020-06-11T09:04:32.079+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2020-06-11T09:04:32.079+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2020-06-11T09:04:32.079+0000 I CONTROL  [initandlisten]
my-replica-set:PRIMARY>
```

**Comment by g3gurung** [comment]
@antonlisovenko thanks anton for the answer.

**Comment by g3gurung** [comment]
one more question.

**Comment by g3gurung** [comment]
@antonlisovenko  BTW incase of sharded cluster. Is it ok to just have one mongos pod in the connection string e.g.
**`mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local`**
or 
all mongos pod should be mentioned e.g. 
**`mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local,mongo-sharded-cluster-mongos-1.mongo-service.mongodb.svc.cluster.local`**

**Comment by nerdeveloper** [comment]
> @antonlisovenko BTW incase of sharded cluster. Is it ok to just have one mongos pod in the connection string e.g.
> **`mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local`**
> or
> all mongos pod should be mentioned e.g.
> **`mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local,mongo-sharded-cluster-mongos-1.mongo-service.mongodb.svc.cluster.local`**

It is a sharded cluster, It has to be all mongos pod

**Comment by antonlisovenko** [comment]
@g3gurung it's highly recommended to list all the ReplicaSet members or Sharded Cluster mongos pods in the mongo URI

**Comment by g3gurung** [comment]
Thanks for the reply guys!
