### ISSUE TITLE
Sharded cluster, server selection error: server selection timeout from istio-injection enabled pod

### ISSUE THREAD

**Issue by g3gurung** [mongodb/mongodb-enterprise-kubernetes#108]
I have a sharded cluster with 2 replicas of mongos pod running. I was able to connect and run queries inside a pod with bash shell. But my apps in GO and NODEJS are not working I have this server selection error in the logs:

>  server selection error: server selection timeout, current topology:  { 
     Type: Unknown, 
     Servers: 
        [
            { Addr: mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local:27017[-120]) incomplete read of message header: read tcp 10.244.0.38:34424->10.244.5.5:27017: read: connection reset by peer }, 
            { Addr: mongo-sharded-cluster-mongos-1.mongo-service.mongodb.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(mongo-sharded-cluster-mongos-1.mongo-service.mongodb.svc.cluster.local:27017[-121]) incomplete read of message header: read tcp 10.244.0.38:34782->10.244.3.5:27017: read: connection reset by peer }, 
        ]
}

**Comment by g3gurung** [comment]
mongoConnString = '**mongodb://mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local:27017,mongo-sharded-cluster-mongos-1.mongo-service.mongodb.svc.cluster.local:27017/testing?ssl=false**'

**Comment by LouisPlisso** [comment]
@g3gurung are you GO and NODEJS apps running inside the cluster?
did you check the service status?

**Comment by g3gurung** [comment]
@LouisPlisso Yes ofcousre both GO and NODEJS apps are in the same cluster with mongodb(sharded).

**Comment by g3gurung** [comment]
```sh
mongoURI := "mongodb://mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local:27017,/mongo-sharded-cluster-mongos-1.mongo-service.mongodb.svc.cluster.local:27017/testing?retryWrites=true&w=majority&ssl=false"
	client, err := mongo.Connect(context.TODO(), options.Client().ApplyURI(mongoURI))
	if err != nil {
		log.Fatalf("mongo connection failed: %v", err)
	}

	log.Println("Start ping.....")
	err = client.Ping(context.TODO(), nil)
	if err != nil {
		log.Fatalf("ping error: %v", err)
	}

	log.Println("Mongo successfully connected")
```

output
```sh
2020/06/15 13:34:43 Start ping.....
2020/06/15 13:35:13 ping error: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : connection(mongo-sharded-cluster-mongos-0.mongo-service.mongodb.svc.cluster.local:27017[-61]) incomplete read of message header: read tcp 10.244.0.40:56416->10.244.5.5:27017: read: connection reset by peer }, ] }
```

**Comment by g3gurung** [comment]
I have istio in my k8 cluster.... istio injection is **enabled** for my GO app. If I **disable** the istio injection then the mongo works fine else the same error.

**Comment by rodrigovalin** [comment]
Hello @g3gurung 

Unfortunatelly we don't have a lot of experience with Istio. I have created an internal ticket for this issue and will come back to you as soon as possible.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
