### ISSUE TITLE
`Values.createCrds` is not used

### ISSUE THREAD

**Issue by igaskin** [mongodb/mongodb-enterprise-kubernetes#111]
The helm chart defines crds outside of the `template` directory, effectively ignoring them.  Also `.Values.createCrds` is not used by the helm chart for its intended purpose.

**Comment by NickSchleicher** [comment]
To add to this, was upgrading from 1.5.3 to 1.5.4, it looks like in 1.5.3 it would only create the necessary CRDs based on the value `watchedResources` this seems to no longer be the case and all CRDs are created, is this intended?

**Comment by rodrigovalin** [comment]
Thanks for the report, 

We changed the way the CRDs are created with our latest release and documentation for this change is still work-in-progress.

Effectively in 1.5.4 to **not** create CRDs you have to use `--skip-crds` (see [Helm docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you)).

The `values-openshit.yaml` file still includes an entry for `createCrds` which is an error; it will be removed with next release (late this week).

**Comment by rodrigovalin** [comment]
@NickSchleicher the crds need to be created manually from `helm_chart/crds` if you used `--skip-crds`. Otherwise all of them will be created.

The `operator.watchedResources` property needs to be set manually. `values.yaml` will make the operator watch over all of the resource types.

**Comment by antonlisovenko** [comment]
Our docs have been updated to reflect changes to Helm resources: https://docs.mongodb.com/kubernetes-operator/master/tutorial/plan-k8s-op-considerations/

Also we've removed `createCrds` parameter from the helm values completely in the latest 1.5.5 release.

I believe this ticket can be closed, feel free to reopen if you still have these issues
