### ISSUE TITLE
chart requires kubeVersion: >=1.13 which is incompatible with Kubernetes v1.16.8-eks-e16311

### ISSUE THREAD

**Issue by ajaychoudhary-nbs** [mongodb/mongodb-enterprise-kubernetes#113]
Kube version compatibility issue because of kubeVersion referred in Chart,yaml.
Potential fix is to ignore this or change this to kubeVersion: '>=1.13-0' so that it can work with more range of versions with string literals.

**Comment by bznein** [comment]
This issue has been fixed with #114. Thanks @ajaychoudhary-nbs for pointing out the issue and proposing a fix!
