### ISSUE TITLE
Backup persistence with Ops Manager after deleting a deployment

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#115]
Hey Guys,
Can't find a way to delete a MongoDB database resource without deleting the snapshots on Ops Manager. It seems like the operator deletes the cluster automatically including all backups.
Is there even a way to do that?
Thanks,
Itay.

**Comment by antonlisovenko** [comment]
Hi @ItayZviCohen 

thanks for your question.

Currently the Operator always terminates backup on MongoDB resource removal and there is no way to avoid this.
We plan to fix this soon and it will get to the next Operator release

**Comment by rodrigovalin** [comment]
Closing this ticket as this has been fixed in latest release.
