### ISSUE TITLE
Cross-Site functionality

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#117]
Hello!
Are there any plans for a Cross-Site functionality between two clusters? My organization is in great need to this feature.
Thanks,
Itay.

**Comment by theburi** [comment]
Hi 
This feature is a definitely something we are looking at and our plan is to start it next month.
Could you describe use case here, please https://feedback.mongodb.com/forums/924355-ops-tools/suggestions/39654730-deploy-mongodb-across-different-kubernetes-cluster
It would help us greatly and also help you to see our progress.

**Comment by ItayZviCohen** [comment]
Hi,
Just commented on the idea :) For anyone who stumbles on this issue and in great need of this feature, please leave your comment here:  https://feedback.mongodb.com/forums/924355-ops-tools/suggestions/39654730-deploy-mongodb-across-different-kubernetes-cluster
Thank you @theburi !

**Comment by rodrigovalin** [comment]
Closing this for now as we have a place for people to add comments on this particular issue.

Thanks again @ItayZviCohen
