### ISSUE TITLE
Cluster config did not pass validation for pre-expansion semantics

### ISSUE THREAD

**Issue by iborba** [mongodb/mongodb-enterprise-kubernetes#119]
Hi.

I've created my ops manager structure following these tutorials:
https://www.mongodb.com/blog/post/introducing-the-mongodb-enterprise-operator-for-kubernetes
https://carlos.mendible.com/2020/02/09/mongodb-enterprise-operator-deploying-mongodb-in-aks/

And ok... the ops manager is running, but I'm not able anyway to create any new deployment.
In all situations i'm getting the following error:

> Error retrieving cluster config from 'http://ops-manager-svc.mongodb.svc.cluster.local:8080/agents/api/automation/conf/v1/5f0c5ff8903b37006f6bca4d?ah=mpn-mongodb-agent-1.mpn-mongodb-agent-service.mongodb.svc.cluster.local&ahs=mpn-mongodb-agent-1&av=10.15.2.6472&aos=linux&aa=x86_64&ab=64&at=1594650529709' : [14:40:13.269] Cluster config did not pass validation for pre-expansion semantics : mongoDbTools field is required if there are any managed MongoDB processes

Anyone knows where did I made a mistake?

Tks

**Comment by LouisPlisso** [comment]
@iborba it seems to be an internal error: can you please send us which versions of the operator and OpsManager (both main and init container) you are using?

Thanks

**Comment by iborba** [comment]
> @iborba it seems to be an internal error: can you please send us which versions of the operator and OpsManager (both main and init container) you are using?
> 
> Thanks

Hi @LouisPlisso, appearently both are in version 9.
