### ISSUE TITLE
Multiple organizations and projects get created

### ISSUE THREAD

**Issue by kurktchiev** [mongodb/mongodb-enterprise-kubernetes#12]
This seems to happen only on the initial install of the operator, but if you install the operator and give it an organization that does not exist, it will create 3 copies (say you name it "test", you will see test/test 3 times under All Organizations). Only one will contain the instances that you have spun up. After the initial one it only creates single organization/project pairs (say you create "test2")

**Comment by antonlisovenko** [comment]
Can you describe your steps in more details please? 
* what is "initial install of the operator" - did any resources exist in K8s/Ops Manager?
* did you specify the `orgId` in the config map? Did you create the group/organization in Ops Manager manually before running Operator?
* do you use Ops Manager or Cloud Manager?

**Comment by kurktchiev** [comment]
> Can you describe your steps in more details please?
> 
> * what is "initial install of the operator" - did any resources exist in K8s/Ops Manager?
helm install mongo-operator --namespace mongo-ops --set namespace=mongo-ops helm_chart/
> * did you specify the `orgId` in the config map? Did you create the group/organization in Ops Manager manually before running Operator?
Specified orgId and did not specify anything in Ops Manager(its a vanilla instance of ops manager)
> * do you use Ops Manager or Cloud Manager?
Ops Manager 4.0.7 vanilla install

**Comment by kurktchiev** [comment]
So yeah it seems if you do the creation in rapid succession the operator ends up barfing and creating multiple organizations and projects. if you do it slowly... it all works as expected, there is some race condition somewhere.

**Comment by jamesbroadhead** [comment]
Tracking internally as CLOUDP-37652

**Comment by antonlisovenko** [comment]
This one is supposed to be fixed in Operator 0.8 https://github.com/mongodb/mongodb-enterprise-kubernetes/releases/tag/0.8, can you please check this please?
