### ISSUE TITLE
kerberos authentication with mongo-db deployment

### ISSUE THREAD

**Issue by ajaychoudhary-nbs** [mongodb/mongodb-enterprise-kubernetes#120]
Hi, 
We want to use kerberos authentication with mongo db deployment however it takes only SCRAM and X509 in authentication mode. Do you support kerberos authentication enabled mongo db deployment with operator? If not, can we enable it manually with ops-manager UI or only these two method will work?  
Thanks

**Comment by LouisPlisso** [comment]
@ajaychoudhary-nbs currently Kerberos authentication is not supported through CRD, but yes you can enable it in the Ops Manager UI

**Comment by ajaychoudhary-nbs** [comment]
@LouisPlisso is there any plan to include this in future release? With ops manager UI, is it possible to do it with some automation script? any automation example would be really help.

**Comment by ItayZviCohen** [comment]
@ajaychoudhary-nbs After a quick search in the docs, I can't see any REST API calls described for Kerberos authentication configuration. Unfortunately that means the only way to configure Kerberos authentication is through the Ops Manager UI.

**Comment by gauravtaneja1984** [comment]
Hello,

I am facing blow error while accessing ops manager using API. Please help me out.

 curl --user '{XXX}:{XXX}' --digest --header 'Accept: application/json' --include  --request GET "<xxx>:<xx>/api/public/v1.0/groups?pretty=true"


Content-Type: application/json
Content-Length: 106

{
  "reason" : "Unauthorized",
  "error" : 401,
  "detail" : "You are not authorized for this resource."
}

**Comment by rodrigovalin** [comment]
@ajaychoudhary-nbs as commented by @ItayZviCohen, there's not way of enabling Kerberos using the Kubernetes MongoDB resources, you will have to use the Ops Manager UI to do that.

**Comment by ajaychoudhary-nbs** [comment]
@ItayZviCohen  @rodrigovalin  Is there any plan to enable kerberos auth with operator? Manual step might not work as we have to mount keytab files manually and if pod restarts then that file might not be available. there is no option also to mount additional volumes.

**Comment by rodrigovalin** [comment]
@ajaychoudhary-nbs this is not planned anytime soon nor any new authentication mechanisms!
