### ISSUE TITLE
Unable to access MongoDB Ops Manager using Public API

### ISSUE THREAD

**Issue by gauravtaneja1984** [mongodb/mongodb-enterprise-kubernetes#121]
Hi Team,
I am trying to access ops manger programmatic but facing below error,could you please let me know how can I fix this. 

 curl --user '{XXX}:{XXX}' --digest --header 'Accept: application/json' --include  --request GET "<xxx>:<xx>/api/public/v1.0/groups?pretty=true"

Content-Type: application/json
Content-Length: 106

{
  "reason" : "Unauthorized",
  "error" : 401,
  "detail" : "You are not authorized for this resource."
}

**Comment by antonlisovenko** [comment]
hi @gauravtaneja1984 

Please double check the keys you use. The URL you've given as an example doesn't need whitelisting - so I assume the only reason for `Unauthorized` can be the wrong keys used. You should use "public_key:private_key" pattern

**Comment by gauravtaneja1984** [comment]
Thanks for the update,but I am passing right public:private keys.

**Comment by rodrigovalin** [comment]
Hello @gauravtaneja1984 

The documentation for the Ops Manager public API can be found here: https://docs.opsmanager.mongodb.com/current/core/api/. Your `curl` command seems to be fine, and I assume you got it from here: https://docs.opsmanager.mongodb.com/current/core/api/#pretty-printing 

Please make sure both parts of the `user` string are passed correctly as: `--user '{USERNAME}:{APIKEY}'` and you should be good.

**Comment by jamesbroadhead** [comment]
Two options for accessing the API include our command-line tool mongocli
https://github.com/mongodb/mongocli

or our golang client 
https://github.com/mongodb/go-client-mongodb-ops-manager

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
