### ISSUE TITLE
Support for deploying a ReplicaSet with Ops Manager w/ self-signed certificate

### ISSUE THREAD

**Issue by ItayZviCohen** [mongodb/mongodb-enterprise-kubernetes#124]
Hey,
Using the operator v1.6 on OpenShift 3.11
Trying to deploy a replicaset when using a VM-based Ops Manager that uses a self-signed certificate for https.
The operator rejects that and throws:
```
Failed to prepare Ops Manager connection ...
... x509: certificate signed by unknown authority
```

Can't find in the docs a section that addresses this situation.

Thanks,
Itay.

**Comment by rodrigovalin** [comment]
Hello,

The docs describing what you need are [here](https://docs.mongodb.com/kubernetes-operator/v1.6/tutorial/create-project-using-configmap/index.html#copy-the-highlighted-section-of-the-following-example-configmap). This basically consists on creating a "Project" `ConfigMap` that includes an entry: `sslRequireValidMMSServerCertificates: "false"`. Make sure to make the value of "false" a String, with double quotes.

This will make the Operator not to try to verify the HTTPS ceritificate contests.

Let me know if you need more help with this.

**Comment by ItayZviCohen** [comment]
Hey!
Double quotes or single quotes (as described in the docs) the Deployment's pod throws:
```
Error while downloading the MongoDB agent ...
Connected to ...
server certificate verification failed. CAfile: ....
```
Thanks,
Itay
