### ISSUE TITLE
Error init-appdb require resource "secrets"

### ISSUE THREAD

**Issue by chuonglh** [mongodb/mongodb-enterprise-kubernetes#125]
Hi Team,

I using docker image _quay.io/mongodb/mongodb-enterprise-init-appdb:1.0.1_ saw this error

`Readiness probe failed: panic: secrets "ops-manager-db-config" is forbidden: User "mongodb-enterprise-appdb" cannot get resource "secrets" in API group ""`

I think it should be **configmaps** not **secrets**

**Comment by rodrigovalin** [comment]
Hello,

We have seen reports of this issue, can you please tell me which version of the operator are you using?

**Comment by chuonglh** [comment]
Hi @rodrigovalin,

The version of operator I'm using is 1.5.5

**Comment by rodrigovalin** [comment]
Hello,

By mistake we overwrote the init-appdb:1.0.1 with a new incompatible version. I have pushed the correct 1.0.1 back to its place. Everything should work now. Make sure you discard the `quay.io/mongodb/mongodb-enterprise-init-appdb:1.0.1` you have. The `imagePullPolicy` of the init-appdb container is set to the default which I think will not try to pull the new image again, and this attribute can't be updated.

**Comment by chuonglh** [comment]
Hi @rodrigovalin,

It works! Thanks for your help.
