### ISSUE TITLE
Unable to create ReplicaSet in mongodb kubernetes operator

### ISSUE THREAD

**Issue by vikasjella26** [mongodb/mongodb-enterprise-kubernetes#129]
I've deployed mongodb kubernetes operator in kubernetes cluster. Operator is deployed and also mongodb opsmanager and Application DB.
But while deploying replicaset its getting failed.

Message: Failed to prepare Ops Manager connection: Error reading or creating project in Ops Manager: Get http://ops-manager-svc.mongodb.svc.cluster.local:8080/api/public/v1.0/orgs?itemsPerPage=500&pageNum=1: dial tcp: lookup ops-manager-svc.mongodb.svc.cluster.local: no such host

When performing curl -v  http://opsmanager-svc.mongodb.svc.cluster.local:8080
![curl](https://user-images.githubusercontent.com/69820033/90440623-2c1e1600-e0f5-11ea-9e4a-43dbf2da9b5b.JPG)

**Comment by antonlisovenko** [comment]
hi @vikasjella26 

Thanks for reporting this.
Which pod are you using to make the `curl` call from?
Ideally it must be the Operator pod.

**Comment by vikasjella26** [comment]
Hi @antonlisovenko 

Yes I'm using operator pod to make curl request.

**Comment by bznein** [comment]
Hi @vikasjella26,

from your message it seems like you might have a typo in your configmap. The error message shows the following url: ` http://ops-manager-svc.mongodb.svc.cluster.local` while the `curl` command you are issuing targets `http://opsmanager-svc.mongodb.svc.cluster.local`.

I believe you just have an extra `-` in your configmap.

**Comment by vikasjella26** [comment]
No That's fine as I was trying with two opsmanagers.

**Comment by bznein** [comment]
Hi @vikasjella26, if from the operator pod you are able to `curl` the operator should be able to have access. 
Just to make sure what the problem actually is and rule out any misconfiguration, can you try with one ops-manager, making sure the url in the configmap and the one you try to `curl` manually are the same?

Thanks
