### ISSUE TITLE
Ability to upgrade instances from Ops Manager

### ISSUE THREAD

**Issue by kurktchiev** [mongodb/mongodb-enterprise-kubernetes#13]
Not being able to upgrade a mongo instance inside Kube is a pretty great shortcoming when deploying this in an enterprise setting that is looking for a single pane of glass for all of their Mongo management needs. Having to manually manipulate objects that are deployed breaks workflows and leaves existing admins trying to figure out how to handle upgrades that up until now have been handled by Ops Manager. Looking for an eta/roadmap/anything on the ability to do upgrades.

**Comment by jamesbroadhead** [comment]
@kurktchiev our current design is that the MongoDs should mostly be managed at the Kube level by modifying the CR definitions. 
We have very rough plans to enable doing this from inside Ops Manager in the future, but they aren't on our immediate roadmap. 

The workflow that we're imagining is that the 'single pane of glass' will be Kube-level UI, so it will be consistent with the applications and other services you are running. We're going to watch how Kube & Openshift add support for UI for CRDs & would consider writing one if their defaults don't provide the right experience
