### ISSUE TITLE
Required configuration property missing: `mmsApiKey`=``.

### ISSUE THREAD

**Issue by zouchengli** [mongodb/mongodb-enterprise-kubernetes#133]
[2020/08/25 04:36:01.447] [.error] [cm/modules/maintainer.go:StartModule:305] <Monitoring Module Manager> [04:36:01.447] Error starting Monitoring module : error parsing settings: `map[maxProcs:0 mmsApiKey: mmsBaseUrl:http://ops-manager-svc.mongodb.svc.cluster.local:8080 mmsGroupId: version:10.2.15.5958]`. Monitoring unable to start. Error: Required configuration property missing: `mmsApiKey`=``. Agent API keys can be found in the UI under Deployment -> Agents -> Agent API Keys.
        at monitoring-agent/components/settings.go:472
        at monitoring-agent/components/settings.go:787
        at monitoring-agent/monitoringexecutor/executor.go:78
        at cm/modules/maintainer.go:304
        at cm/modules/maintainer.go:193
        at cm/modules/maintainer.go:73
        at louisaberger/procexec/concurrency.go:45
        at src/runtime/asm_amd64.s:1357

**Comment by zouchengli** [comment]
this is my ops manager yaml content:
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  # the number of Ops Manager instances to run. Set to value bigger
  # than 1 to get high availability and upgrades without downtime
  replicas: 3

  # the version of Ops Manager distro to use
  version: 4.4.1

  # optional. Specify the custom cluster domain of the Kubernetes cluster if it's different from the default one ('cluster.local').
  # This affects the urls generated by the Operator.
  # This field is also used for Application Database url
  clusterDomain: cluster.local

  # the name of the secret containing admin user credentials.
  # Either remove the secret or change the password using Ops Manager UI after the Ops Manager
  # resource is created!
  adminCredentials: ops-manager-admin-secret

  # optional. The Ops Manager configuration. All the values must be of type string
  configuration:
    mms.fromEmailAddr: "admin@thecompany.com"
    # this enables local mode in Ops Manager
    automation.versions.source: local
  backup:
    enabled: false

  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    # optional. Configures the version of MongoDB used as an application database.
    # The bundled MongoDB binary will be used if omitted and no download from the Internet will happen
    #version: 4.2.6-ent
    persistent: true
    # optional. Allows to pass custom MongoDB process configuration
    additionalMongodConfig:
      operationProfiling:
        mode: slowOp
    podSpec:
      cpu: '0.25'
      memory: 512M
      persistence:
        multiple:
          data:
            storage: 10Gi
            storageClass: mongodb-storage
          journal:
            storage: 1Gi
            storageClass: mongodb-storage
          logs:
            storage: 500M
            storageClass: mongodb-storage

**Comment by zouchengli** [comment]
`---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  # the number of Ops Manager instances to run. Set to value bigger
  # than 1 to get high availability and upgrades without downtime
  replicas: 3

  # the version of Ops Manager distro to use
  version: 4.4.1

  # optional. Specify the custom cluster domain of the Kubernetes cluster if it's different from the default one ('cluster.local').
  # This affects the urls generated by the Operator.
  # This field is also used for Application Database url
  clusterDomain: cluster.local

  # the name of the secret containing admin user credentials.
  # Either remove the secret or change the password using Ops Manager UI after the Ops Manager
  # resource is created!
  adminCredentials: ops-manager-admin-secret

  # optional. The Ops Manager configuration. All the values must be of type string
  configuration:
    mms.fromEmailAddr: "admin@thecompany.com"
    # this enables local mode in Ops Manager
    automation.versions.source: local
  backup:
    enabled: false

  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    # optional. Configures the version of MongoDB used as an application database.
    # The bundled MongoDB binary will be used if omitted and no download from the Internet will happen
    #version: 4.2.6-ent
    persistent: true
    # optional. Allows to pass custom MongoDB process configuration
    additionalMongodConfig:
      operationProfiling:
        mode: slowOp
    podSpec:
      cpu: '0.25'
      memory: 512M
      persistence:
        multiple:
          data:
            storage: 10Gi
            storageClass: mongodb-storage
          journal:
            storage: 1Gi
            storageClass: mongodb-storage
          logs:
            storage: 500M
            storageClass: mongodb-storage`

**Comment by zouchengli** [comment]
My kuberneters cluster version v1.13.12

**Comment by zouchengli** [comment]
I use kubernters cluster version v1.18.6 occur same probleam
{"logType":"automation-agent-verbose","contents":"[2020/08/25 06:05:56.812] [.error] [cm/modules/maintainer.go:mainLoop:194] <Monitoring Module Manager> [06:05:56.812] Error starting new module : <Monitoring Module Manager> [06:05:56.812] Error starting Monitoring module : error parsing settings: `map[maxProcs:0 mmsApiKey: mmsBaseUrl:http://ops-manager-svc.mongodb.svc.cluster.local:8080 mmsGroupId: version:10.2.15.5958]`. Monitoring unable to start. Error: Required configuration property missing: `mmsApiKey`=``. Agent API keys can be found in the UI under Deployment -> Agents -> Agent API Keys."}

**Comment by pi-xel** [comment]
Hi, I upgraded to the latest version of ops manager (from 4.2.10 I believe) and enterprise operator (from 1.5.2) and am now running into the same issue. In addition, the operator gets into a crashloop as soon as all ops-manager-db instances get into a running state. Do you have any idea what could be going wrong?

**Comment by pi-xel** [comment]
One thing I noticed is that in the AppDB StatefulSet the environment variables AGENT_API_KEY and GROUP_ID are not set, as opposed to all other databases in my cluster. Setting these manually in thr StatefulSet briefly fixes the issue, but these changes are immediately overwritten by the operator.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
