### ISSUE TITLE
mongodb state OPSMANAGER Failed APPDB Reconciling

### ISSUE THREAD

**Issue by zouchengli** [mongodb/mongodb-enterprise-kubernetes#135]
The old kubernetes version:
![image](https://user-images.githubusercontent.com/27568522/91150982-a6e7c200-e6ef-11ea-9930-7c2245856ca6.png)

**Comment by zouchengli** [comment]
The new kubernetes version:
![image](https://user-images.githubusercontent.com/27568522/91151208-f6c68900-e6ef-11ea-8fba-54cab63b4b18.png)

**Comment by bznein** [comment]
Hi @zouchengli thanks for the report

Could you try showing us the operator logs? That might help us identify what is the issue

Thanks

**Comment by zouchengli** [comment]
> Hi @zouchengli thanks for the report
> 
> Could you try showing us the operator logs? That might help us identify what is the issue
> 
> Thanks

![image](https://user-images.githubusercontent.com/27568522/91250889-abae8380-e78c-11ea-8e7a-a23457bae95d.png)
Oh, thank you for your attention in advance. I tried to change to an old release version yesterday, and today it seems that there is no problem temporarily.

**Comment by zouchengli** [comment]
> > Hi @zouchengli thanks for the report
> > Could you try showing us the operator logs? That might help us identify what is the issue
> > Thanks
> 
> ![image](https://user-images.githubusercontent.com/27568522/91250889-abae8380-e78c-11ea-8e7a-a23457bae95d.png)
> Oh, thank you for your attention in advance. I tried to change to an old release version yesterday, and today it seems that there is no problem temporarily.

But occur another problem
![image](https://user-images.githubusercontent.com/27568522/91252242-c9c9b300-e78f-11ea-8ac7-1ec4f8d2153b.png)

**Comment by zouchengli** [comment]
The agents all unstable

**Comment by zouchengli** [comment]
I'm follow trace log:
Failure sending ping to Server. Op: Post Err: dial tcp 220.250.64.225:8080: i/o timeout
	at monitoring-agent/components/server.go:254
	at monitoring-agent/components/status.go:128
	at monitoring-agent/components/status.go:175
	at monitoring-agent/components/status.go:200
	at louisaberger/procexec/concurrency.go:45
	at src/runtime/asm_amd64.s:1357
why send ping 220.250.64.225 this ip?

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
