### ISSUE TITLE
Is this free of charge or not?

### ISSUE THREAD

**Issue by nikosece** [mongodb/mongodb-enterprise-kubernetes#136]
I am bit confused. I want to run this at my cluster , consisting of 3 physical manchines, without any cloud providers. Can i use it for  free or i have to pay? I am asking because at installation steps i din't see any step about mongo sign in

**Comment by theburi** [comment]
This solution is for MongoDB Enterprise and requires MongoDB Enterprise advanced license.

For a free to use MongoDB community edition we have a different project https://github.com/mongodb/mongodb-kubernetes-operator
