### ISSUE TITLE
Can we change the URL of Ops-manager created by MongoDB Kubernetes Operator 1.7.1

### ISSUE THREAD

**Issue by vikasjella26** [mongodb/mongodb-enterprise-kubernetes#142]
I'm trying to run Ops-manager created with MongoDB Kubernetes Operator 1.7.1 over HTTPS.
While running without HTTPS able to deploy Ops-manager and Deploy the Replicaset too. But while running over HTTPS it's asking for TLS/SSL certificates. I've provided the certificates generated with my organization, but throwing an error like

Error:  logType : "automation-agent-stderr", "contents" : "Failure sending ping to server. Op: Post Err: x509: certificates is valid for xx-xxxxxx-xxxxxxxx, not opsmanager-svc.mongodb.svc.cluster.local".

is there any way to resolve the Ops-manager URI to our desired URI.

**Comment by theburi** [comment]
Hi. You could use https://docs.opsmanager.mongodb.com/current/reference/configuration/#mms.centralUrl
However, that will force all the internal communication with opsmanager  via Ingress. (there is a configuration parameter in OpsManager CRD)
Another option would be to add opsmanager-svc.mongodb.svc.cluster.local to Cert SN.

**Comment by jamesbroadhead** [comment]
@vikasjella26 It sounds like you will need to generate and pass different TLS certificates which match the OM hostname that the Agent is using. 

The MongoDB support team should be able to help guide you through it - https://support.mongodb.com/welcome
