### ISSUE TITLE
MongoDB Enterprise Operator NA for ppc64le arch

### ISSUE THREAD

**Issue by krishvoor** [mongodb/mongodb-enterprise-kubernetes#147]
Team,

I have currently tried MongoDB Enterprise Operator on OpenShift Cluster Platform 4.X on IBM’s ppc64le architecture - via steps mentioned here -
https://docs.mongodb.com/kubernetes-operator/stable/tutorial/install-k8s-operator/

However, to my surprise, I have not found ppc64le equivalent docker images for the following -

quay.io/mongodb/mongodb-enterprise-operator:1.7.1 https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise.yaml#L201

quay.io/mongodb/mongodb-enterprise-database https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise.yaml#L214

quay.io/mongodb/mongodb-enterprise-ops-manager https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise.yaml#L218

quay.io/mongodb/mongodb-enterprise-init-ops-manager https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise.yaml#L220

quay.io/mongodb/mongodb-enterprise-init-appdb https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise.yaml#L224

quay.io/mongodb/mongodb-enterprise-appdb - https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise.yaml#L230

Can you perhaps tell me, how can I help contribute towards enabling ppc64le docker images?

Thanks,
Harsha.

**Comment by theburi** [comment]
Hi. At the moment we don't support ppc64le for Enterprise operator. It is on our long-term agenda as part of IBM partnership. Not to mention we do support MongoDB and OpsManager for ppc64le.

We do have an Open Source project for Community MongoDB. https://github.com/mongodb/mongodb-kubernetes-operator
That project would be a much better contribution platform if you have interested in bringing MongoDB to Kubernetes on Power.

**Comment by krishvoor** [comment]
@theburi  - Thanks for the insights, will reach out to MongoDB (Commnunity) Kubernetes Operator.
