### ISSUE TITLE
MongoDB Operator 1.8 for OpenShift is missing OpenShift Route

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#150]
The provisioning of the Ops Manager went successfully but there are no OpenShift Routes so that people on the network can access the Ops Manager UI. 

<img width="1451" alt="Screen Shot 2020-10-22 at 11 12 07 PM" src="https://user-images.githubusercontent.com/749093/96962607-07129e80-14bc-11eb-89b1-6d2b1d12edca.png">

**Comment by theburi** [comment]
Hi
At the moment we are not creating OpenShift Route by default. Ingress to OpsManager could be configured in a multitude of ways and at the moment we don't make that choice for the User. 
We will add extra steps to our docs to highlight OpenShift Route configuration.

**Comment by alberttwong** [comment]
https://jira.mongodb.org/browse/DOCSP-12928.

Great.  I opened a JIRA ticket and I can help with writing the extra steps.
