### ISSUE TITLE
Enterprise Operator says community support?

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#153]
Shouldn't the enterprise operator say commercial support?

<img width="944" alt="Screen Shot 2020-10-22 at 11 32 09 PM" src="https://user-images.githubusercontent.com/749093/96964198-e6981380-14be-11eb-8111-120004d6ebf4.png">

**Comment by theburi** [comment]
Thank you for bringing it to our attention. We will get it fixed.

**Comment by alberttwong** [comment]
https://jira.mongodb.org/browse/DOCSP-12927
