### ISSUE TITLE
Documentation is unclear that Operator only supports Ops Manager based organizations in cloud.mongodb.com and not Atlas-based organizations.

### ISSUE THREAD

**Issue by alberttwong** [mongodb/mongodb-enterprise-kubernetes#155]
Documentation is unclear that Operator only supports Ops Manager based organizations in cloud.mongodb.com and not Atlas-based organizations.

**Comment by JuliaMongo** [comment]
@alberttwong please review and approve this PR:https://github.com/10gen/docs-k8s-operator/pull/416
