### ISSUE TITLE
recreation of MongoDBOpsManager fails with USER_ALREADY_EXISTS error code

### ISSUE THREAD

**Issue by Panos512** [mongodb/mongodb-enterprise-kubernetes#159]
When recreating the Ops Manager it fails with:

`Failed to create an admin user in Ops Manager: Status: 409 (Conflict), ErrorCode: USER_ALREADY_EXISTS, Detail: A user with username <> already exists.`

APPDB is on a Running state.

Even when I change the secret to create a different user it creates the user (I can see that in the UI) and it then proceeds to fail again.

**Comment by alberttwong** [comment]
What container/kube environment? Is this a brand new installation?  What was the sequence of steps that you executed to get to this point?   What UI are you talking about?

**Comment by Panos512** [comment]
Hi Albert, thank you very much for your reply and sorry for the delay. I'll close the issue as it hasn't reappeared.
Here are some more details in case you re interested: 

It was a new installation on an OpenStack magnum cluster (running k8s v1.18.6). I was talking about the ops manager UI. I was following the official documentation and I was at the step before deploying a db resource. After deleting the `om` resource it was automatically being recreated (as it should) but it was failing because the user already existed.
