### ISSUE TITLE
Using Cloud Atlas instead of Ops Manager

### ISSUE THREAD

**Issue by cipriantarta** [mongodb/mongodb-enterprise-kubernetes#16]
I'm having some difficulties setting up the k8s operator in cloud atlas.
I'm getting this warning:
`{"level":"warn","ts":1553867870.7270057,"caller":"operator/groupshelper.go:77","msg":"Failed to update tags for group: Status: 404 (Not Found), ErrorCode: ATLAS_GROUP, Detail: Group **************** is an Atlas group; use the Atlas Public API at /api/atlas/v1.0 to access it.","ShardedCluster":"mongodb/mongodb-cluster","project":"*****"}`

Is this actually supported and if yes, where do I make th change to use the atlas API instead of the public one?
I expected that my cluster will show up on my Atlas page after it successfully installed in k8s. Is my assumption wrong?

Thanks

**Comment by antonlisovenko** [comment]
Yes, we have an internal ticket for this and plan to fix this before GA. 
This doesn't affect the correctness of work of the Operator and MongoDB resources that it has created, also all the communication with Atlas will work as expected, just some additional configuration for the group is not set up which affects some cosmetic things related to Atlas UI. 

Thanks for posting this, we'll add an update as soon as this bug is fixed

**Comment by cipriantarta** [comment]
Thanks for the quick feedback on this. Is it safe to assume that there's
currently no workaround for this issue and best to wait for the fix?

**Comment by antonlisovenko** [comment]
This warning in the log doesn't affect the correctness in any way, you can just ignore this so far
So you can continue using the Operator with the only  caution that we are not officially GA so far.
One important note: the group and organization that was created by the Operator doesn't have "Atlas" type, but it's "Cloud Manager" - you can see it in the label in the top-left corner. I've updated the previous message as I wasn't correct there - the Operator can work only with Ops Manager and Cloud Manager, but Atlas provides its own way of database provisioning and management

**Comment by cipriantarta** [comment]
I think the confusion comes from the fact that I used an existing orgId. Which is an Atlas organization. 
The operator managed to create a new project in said organisation, but failed to add the cluster into the project.
Perhaps the operator should forbid using orgId of atlas organizations?
Anyway, I'll give it another try w/o specifying the orgId.

**Comment by antonlisovenko** [comment]
Yes, you are right, you either need to use the existing organization with type CloudManager or let the Operator create it (so don't specify the orgId)

**Comment by antonlisovenko** [comment]
Btw I've missed the error message you posted in the first post. It in fact means that Operator doesn't work with Atlas - only Cloud Manager or Ops Manager. 

In case of using Cloud Manager you'll see some warning in the logs with the same text "Failed to update tags for group" which is exactly what I meant - you can just ignore it.

**Comment by cipriantarta** [comment]
Got it now. Good we got to the bottom of it and thanks for your help. Much
appreciated.
