### ISSUE TITLE
Cloud Manager shows wrong node memory allocation

### ISSUE THREAD

**Issue by briben** [mongodb/mongodb-enterprise-kubernetes#17]
When creating a new Replica Set with the Kubernetes Operator, the nodes appear in Cloud Manager with an incorrect amount of RAM.

I have created a 5-node Replica Set with 0.25 CPU and 512MiB RAM, but in Cloud Manager they are listed as having 64GB RAM. This appears to be taken from the Kubernetes host worker node which **does have** 64GB RAM.

Also, will this affect the memory allocation available from our Enterprise license?

Snippet of container resources from output of: `$ kubectl describe pods test-replica-set-0`

```
Containers:
  mongodb-enterprise-database:
    Container ID:   docker://0933005a001651ba783f01267acd20c92a2fb45708a5c6a89a1357321cf6f759
    Image:          quay.io/mongodb/mongodb-enterprise-database:0.7
    Image ID:       docker-pullable://quay.io/mongodb/mongodb-enterprise-database@sha256:dd3c426be68c99eb77dabbc3e320553f647c1fe380cf3fea39ab6038e6c6e30a
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 02 Apr 2019 13:49:57 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     250m
      memory:  512M
    Requests:
      cpu:     250m
      memory:  512M
```

![test-rs-5-nodes](https://user-images.githubusercontent.com/18284211/55415000-2194c800-5564-11e9-9983-df6f45a9857e.png)

**Comment by jamesbroadhead** [comment]
Thanks for the bug report! 

Yes, this is incorrect -- we'll file a ticket to get this fixed. 

For licensing purposes (assuming you are on the RAMPool), the container's RAM should be counted. For more specifics on licensing, please speak with your Account Manager.

**Comment by briben** [comment]
Thanks for the quick response James!

**Comment by antonlisovenko** [comment]
The issue should be fixed by now, feel free to reopen if it's still not working correctly
