### ISSUE TITLE
Ops-Manager in (0/1) Running state after Application Database Restart.

### ISSUE THREAD

**Issue by vikasjella26** [mongodb/mongodb-enterprise-kubernetes#183]
**What did you do to encounter the bug?**
I've installed the MongoDB Kubernetes Operator and while deploying the Ops-Manager after the Application Database restart the pods went into (0/1) Running State.

**What did you expect?**
I expect the Running Ops-Manager and It's Replicaset.

**What happened instead?**
After deploying the Ops-manager Pods went into (0/1) running state.

**Screenshots**
![image](https://user-images.githubusercontent.com/69820033/107150159-6ff62780-6982-11eb-84cf-42c297f1eb77.png)

**Operator Information**
 - Operator Version: MongoDB Enterprise Kubernetes Operator v1.9
 - Base Images used ubuntu

**Ops Manager Information**
 - Ops Manager Version : v4.4.4
 - Ops Manager managed by the Operator.
 - Tried Ops Manager in Local Mode and Hybrid Mode.

**Kubernetes Cluster Information**
 - Distribution: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-06-03T10:13:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-06-03T10:06:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
 - Image Registry location : quay

If possible, please include:
 - `kubectl logs -n mongodb ops-manager-0 ` output
 - 2021-02-07T14:59:42.330+0000 [MmsLogAppender-1] WARN  com.xgen.svc.mms.util.MongoAppender [MongoAppender.java.periodicExceptionLog:116] - Failed to write batch of 26 log events
com.mongodb.MongoTimeoutException: Timed out after 20000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@3e8cddc7. Client view of cluster state is {type=REPLICA_SET, servers=[{address=ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoCommandException: Command failed with error 211 (KeyNotFound): 'Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1612553935, 4) } with id: 6925864811838308355' on server ops-manager-db-1.ops-manager-db-svc.mongodb.svc.cluster.local:27017. The full response is {"ok": 0.0, "errmsg": "Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1612553935, 4) } with id: 6925864811838308355", "code": 211, "codeName": "KeyNotFound"}}}, {address=ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoCommandException: Command failed with error 211 (KeyNotFound): 'Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1612553935, 4) } with id: 6925864811838308355' on server ops-manager-db-2.ops-manager-db-svc.mongodb.svc.cluster.local:27017. The full response is {"ok": 0.0, "errmsg": "Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1612553935, 4) } with id: 6925864811838308355", "code": 211, "codeName": "KeyNotFound"}}}, {address=ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoCommandException: Command failed with error 211 (KeyNotFound): 'Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1612553935, 4) } with id: 6925864811838308355' on server ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local:27017. The full response is {"ok": 0.0, "errmsg": "Cache Reader No keys found for HMAC that is valid for time: { ts: Timestamp(1612553935, 4) } with id: 6925864811838308355", "code": 211, "codeName": "KeyNotFound"}}}]

 - yaml definitions for your objects
 - apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  replicas: 1
  version: 4.4.1
  #featureCompatibilityVersion: 4.2.10
  adminCredentials: ops-manager-admin-secret
  configuration:
    #automation.versions.source: mongodb
    mms.ignoreInitialUiSetup: "true"
    mms.centralUrl: "http://153.88.15.139:8080"
    mms.fromEmailAddr: "vikas.jella@ericsson.com"
    mms.replyToEmailAddr: "vikas.jella@ericsson.com"
    mms.adminEmailAddr: "vikas.jella@ericsson.com"
    mms.mail.transport: "smtp"
    mms.mail.hostname: "localhost"
    mms.mail.port: "25"
    mms.minimumTLSVersion: "TLSv1.2"
  externalConnectivity:
    type: LoadBalancer
  applicationDatabase:
    members: 3
    version: 4.2.6-ent
    persistent: false
    passwordSecretKeyRef:
      name: app-db-admin-secret
  backup:
    enabled: false

 - Kubectl logs -n mongodb ops-manager-db-0
 - {"logType":"automation-agent-stdout","contents":"<ops-manager-db-0> [15:00:45.160] Running step 'WaitFeatureCompatibilityVersionCorrect' as part of move 'WaitFeatureCompatibilityVersionCorrect'"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:44.661] [.info] [cm/mongoctl/replsetctl.go:RsMemberCanPerformGlobalAction:468] <ops-manager-db-0> [15:00:44.661] Mongod (ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local:27017) cannot perform Global Update Action because there is no healthy primary in the replica set."}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:44.661] [.info] [cm/mongoctl/globalaction.go:MongodCanPerformGlobalAction:296] <ops-manager-db-0> [15:00:44.661] Mongod cannot perform Global Update Action because other members of rs set are not done"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:44.758] [.info] [main/components/agent.go:LoadClusterConfig:197] [15:00:44.758] clusterConfig unchanged"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:45.160] [.info] [cm/director/director.go:computePlan:269] <ops-manager-db-0> [15:00:45.160] ... process has a plan : WaitFeatureCompatibilityVersionCorrect"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:45.160] [.info] [cm/director/director.go:executePlan:876] <ops-manager-db-0> [15:00:45.160] Running step 'WaitFeatureCompatibilityVersionCorrect' as part of move 'WaitFeatureCompatibilityVersionCorrect'"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:45.160] [.info] [cm/director/director.go:tracef:781] <ops-manager-db-0> [15:00:45.160] Precondition of 'WaitFeatureCompatibilityVersionCorrect' applies because "}
{"logType":"automation-agent-verbose","contents":"[All the following are true: "}
{"logType":"automation-agent-verbose","contents":"    ['currentState.Up' = true]"}
{"logType":"automation-agent-verbose","contents":"]"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:45.160] [.info] [cm/director/director.go:planAndExecute:544] <ops-manager-db-0> [15:00:45.160] Step=WaitFeatureCompatibilityVersionCorrect as part of Move=WaitFeatureCompatibilityVersionCorrect in plan failed : <ops-manager-db-0> [15:00:45.160] Postcondition not yet met for step WaitFeatureCompatibilityVersionCorrect because "}
{"logType":"automation-agent-verbose","contents":"[<Current FeatureCompatibilityVersion =  is not equal to desired = 4.2 >]."}
{"logType":"automation-agent-verbose","contents":" Recomputing a plan..."}
{"logType":"automation-agent-stderr","contents":"[2021/02/07 15:00:45.965] [agent.error] [components/agent.go:Iterate:171] Failed to fetch Conf"}
{"logType":"automation-agent-stderr","contents":"Unexpected conf response from server: `Response Status: 500 Internal Server Error Err: `"}
{"logType":"automation-agent-stderr","contents":"\tat monitoring-agent/components/server.go:172"}
{"logType":"automation-agent-stderr","contents":"\tat monitoring-agent/components/server.go:219"}
{"logType":"automation-agent-stderr","contents":"\tat monitoring-agent/components/agent.go:169"}
{"logType":"automation-agent-stderr","contents":"\tat monitoring-agent/components/agent.go:261"}
{"logType":"automation-agent-stderr","contents":"\tat monitoring-agent/monitoringexecutor/executor.go:125"}
{"logType":"automation-agent-stderr","contents":"\tat louisaberger/procexec/concurrency.go:45"}
{"logType":"automation-agent-stderr","contents":"\tat src/runtime/asm_amd64.s:1357"}
{"logType":"automation-agent-stderr","contents":"[2021/02/07 15:00:45.965] [agent.info] [components/agent.go:Run:266] Done. Sleeping for 7s..."}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:45.759] [.info] [main/components/agent.go:LoadClusterConfig:197] [15:00:45.759] clusterConfig unchanged"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:46.362] [.info] [cm/mongoclientservice/mongoclientservice.go:func1:1364] [15:00:46.362] Testing auth with username __system db=local to ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local:27017 (local=false) connectMode=SingleConnect ipversion=0 tls=false"}
{"logType":"automation-agent-verbose","contents":"[2021/02/07 15:00:46.452] [.info] [cm/mongoctl/processctl.go:GetKeyHashes:1742] <ops-manager-db-0> [15:00:46.452] Able to successfully auth to ops-manager-db-0.ops-manager-db-svc.mongodb.svc.cluster.local:27017 (local=false) using desired auth key"}
{"logType":"mongodb","contents":"2021-02-07T15:00:46.260+0000 I  NETWORK  [conn78] end connection 192.168.217.182:37380 (15 connections now open)"}
{"logType":"mongodb","contents":"2021-02-07T15:00:46.260+0000 I  NETWORK  [conn77] end connection 192.168.217.182:37374 (14 connections now open)"}

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 
If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
