### ISSUE TITLE
Are there any plans to base MongoDB operator and/or database on rhel?

### ISSUE THREAD

**Issue by bsuro10** [mongodb/mongodb-enterprise-kubernetes#22]
Hey,
I noticed that your MongoDB operator and database are based on Ubuntu image and just wanted to ask if there are any plans in the future to extend the images to be based on rhel image?

**Comment by antonlisovenko** [comment]
Hi

We have support for rhel already: https://access.redhat.com/containers/?tab=overview&platform=docker#/registry.connect.redhat.com/mongodb/enterprise-operator

**Comment by bsuro10** [comment]
@antonlisovenko Wow thats great! 
Couldn't find anything about that in the doc at github or the official site,
all i could manage to find (just now) is this mention:

> MongoDB builds the container images from the latest Ubuntu 16.04 and Red Hat Enterprise Linux 7

It will be great if you can add it on github or at the official site as another repository to pull from :)
