### ISSUE TITLE
Does operator work with MongoDB Community Edition

### ISSUE THREAD

**Issue by andrii-litvinov** [mongodb/mongodb-enterprise-kubernetes#23]
I searched the web and couldn't find any info on whether k8s operator will work with MongoDB Community Edition. Could you please clarify it?

**Comment by delgod** [comment]
I believe Ops Manager subscription needed.

Andrii, you can also consider https://github.com/percona/percona-server-mongodb-operator

**Comment by andrii-litvinov** [comment]
I have Cloud Manager subscription, but not sure if operator can work with CE instances.

I will check, thank you!

**Comment by jamesbroadhead** [comment]
Yes, you can use Community MongoDB. This is controlled with the 'version' field in the CR -- https://docs.mongodb.com/kubernetes-operator/stable/tutorial/deploy-standalone/
