### ISSUE TITLE
Add MongoDB Enterprise Operator 1.0 to OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [mongodb/mongodb-enterprise-kubernetes#24]
The latest version of the operator on OperatorHub.io is 0.9. Add version 1.0 to OperatorHub.io.

**Comment by jamesbroadhead** [comment]
Thanks for reporting -- filed CLOUDP-46155 internally to track this

**Comment by antonlisovenko** [comment]
The issue is fixed and the latest Operator version is released to OperatorHub.io on each new release
