### ISSUE TITLE
Operator checking ConfigMaps unrelated to mdb

### ISSUE THREAD

**Issue by NickSchleicher** [mongodb/mongodb-enterprise-kubernetes#25]
Version: 1.0

The mongodb operator was configured like so:
```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
  namespace: core
spec:
  version: {{ .Values.version }}
  project: mongodb-enterprise-operator
  credentials: mongodb-enterprise-operator
  type: ReplicaSet
...
```
It is using project `mongodb-enterprise-operator` and a ConfigMap exists in the namespace with that name. Everything sets up correctly, but when I create another ConfigMap (`cache-config`) in the same namespace which is used for an unrelated deployment - the logs spam
```
{"level":"error","ts":1564493122.0237124,"caller":"operator/project_controller.go:83","msg":"error getting config map Property \"baseUrl\" is not specified in config map core/cache-config","Project":"core/cache-config","stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ProjectReconciler).Reconcile\n\t/data/mci/d8740a786a06732043649947e7e73f5b/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/project_controller.go:83\ngithub.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/data/mci/d8740a786a06732043649947e7e73f5b/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/data/mci/d8740a786a06732043649947e7e73f5b/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/data/mci/d8740a786a06732043649947e7e73f5b/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/data/mci/d8740a786a06732043649947e7e73f5b/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/data/mci/d8740a786a06732043649947e7e73f5b/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

I think this is from the setup assuming that everything is launched in it's own mongodb namespace and there would not be any non mongodb resources in there

**Comment by antonlisovenko** [comment]
hi @NickSchleicher 
Thanks for your report
this was supposed to be fixed in 1.0
Can you please try 1.1 and say if you still have this issue?

**Comment by NickSchleicher** [comment]
@antonlisovenko sorry just updated and see that it is no longer an issue
thanks!

**Comment by boyang121** [comment]
@antonlisovenko looks like this is still an issue in v1.1

`{"level":"error","ts":1565218113.040875,"caller":"operator/common_controller.go:205","msg":"Failed to create/update the StatefulSet: Statefulset or its pods failed to reach READY state. Check the events for statefulset and pods: kubectl describe sts fx-fico-pto-tenant-1o3jxolwlt-prod-01-fxrs-shard -n fico-pto-tenant-1o3jxolwlt-design-falconx; kubectl describe po fx-fico-pto-tenant-1o3jxolwlt-prod-01-fxrs-shard-0 -n fico-pto-tenant-1o3jxolwlt-design-falconx;...","ReplicaSet":"fico-pto-tenant-1o3jxolwlt-design-falconx/fx-fico-pto-tenant-1o3jxolwlt-prod-01-fxrs-shard","stacktrace":"github.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileCommonController).updateStatusFailed\n\t/data/mci/abaee30173a72c583528f8d1fb4c26c0/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/common_controller.go:205\ngithub.com/10gen/ops-manager-kubernetes/pkg/controller/operator.(*ReconcileMongoDbReplicaSet).Reconcile\n\t/data/mci/abaee30173a72c583528f8d1fb4c26c0/src/github.com/10gen/ops-manager-kubernetes/pkg/controller/operator/mongodbreplicaset_controller.go:98\ngithub.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/data/mci/abaee30173a72c583528f8d1fb4c26c0/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/data/mci/abaee30173a72c583528f8d1fb4c26c0/src/github.com/10gen/ops-manager-kubernetes/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/data/mci/abaee30173a72c583528f8d1fb4c26c0/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/data/mci/abaee30173a72c583528f8d1fb4c26c0/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/data/mci/abaee30173a72c583528f8d1fb4c26c0/src/github.com/10gen/ops-manager-kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}`
