### ISSUE TITLE
Assigning fixed port number of NodePort *-external

### ISSUE THREAD

**Issue by nststanev** [mongodb/mongodb-enterprise-kubernetes#30]
When the service for MongoDB deployment is specified as exposedExternally, the port number is assigned randomly. Even if I change it manually after creation, it gets changed at some moment.
I would like to have a fixed port for the NodePort - ideally specified somewhere in yml.
The only workaround I found so far is to create a standalone NodePort service in the same namespace

**Comment by antonlisovenko** [comment]
hi @nststanev 

thanks for your report.
We have plans to support proper external connectivity some time later. This means it will be possible to connect to replica sets from outside of K8s cluster. May be we'll consider custom NodePort port configuration then. For now I think you could play with `exposedExternally: false` and providing your own custom NodePort service.

**Comment by nststanev** [comment]
Hi @antonlisovenko thanks

**Comment by antonlisovenko** [comment]
The bug was fixed in Operator 1.3.0
