### ISSUE TITLE
Agent x509 certificates have not yet been created

### ISSUE THREAD

**Issue by andrii-litvinov** [mongodb/mongodb-enterprise-kubernetes#31]
I have ConfigMap and MongoDB resources in different namespaces in order to deploy multiple clusters in same project in Cloud Manager. Everything works fine unless I configure x509 authentication for the project. Once authentication is enabled and all CSRs are approved and issued, MDB resource gets stuck in Pending state with message "Agent x509 certificates have not yet been created". Is there a way to make it work with ConfigMap and MongoDB in separate namespaces? Is is a bug or unsupported case? If latter, how is it possible to create multiple cluster in same project in Cloud Manager?

Operator version is 1.2.2.

**Comment by chatton** [comment]
Hi @andrii-litvinov, the operator will mount the sceret "agent-certs" into the replica set pods. However, there is a Kubernetes limitation which requires the secret to exist in the same namespace as the pods (in this case the MongoDB resource) so unfortunately it is currently not possible to mount agent certificates in a different namespace. 

Reference: https://kubernetes.io/docs/concepts/configuration/secret/#restrictions
