### ISSUE TITLE
Username/password authentication

### ISSUE THREAD

**Issue by andrii-litvinov** [mongodb/mongodb-enterprise-kubernetes#32]
The [doc](https://docs.mongodb.com/kubernetes-operator/stable/tutorial/manage-database-users-x509/) says that only X.509 authentication is supported, but I read [in release notes](https://docs.mongodb.com/kubernetes-operator/stable/release-notes/#k8s-op-full-1-2-2) that it is somehow possible.

I tried to use Cloud Manger public API to enable MONGODB-CR authentication for automation agent and for the deployments, but got BadRequest response with message "Something went wrong validating your Automation Config. Sorry!" which does not help much.

I couldn't find any information if username/password will ever be supported by the Operator. Could you please clarify it?

**Comment by jamesbroadhead** [comment]
Yes, it is on our immediate roadmap. 
We don't publish intended release dates, but we're working on it at the moment. 

If you'd like to talk some more about it, and to see if your timeline works with ours, please open a support case.

**Comment by andrii-litvinov** [comment]
Thank you for clarification! I will open a support case.

I wrote about MONGODB-CR because that is the only value for username/password auth in the [doc](https://docs.cloudmanager.mongodb.com/reference/api/automation-config/#authentication).
