### ISSUE TITLE
Missing `specDescriptors` in MongoDB Operator CSV

### ISSUE THREAD

**Issue by OchiengEd** [mongodb/mongodb-enterprise-kubernetes#34]
The Cluster Service Version(CSV) for the MongoDB operator versions `v1.1.0`, `v1.2.1` and `v1.2.2` no longer contain the Operator Lifecycle Manager(OLM) specDescriptors. See https://github.com/operator-framework/community-operators/blob/efda5dc98fd580ab5f1115a50a28825ae4fe6562/upstream-community-operators/mongodb-enterprise/mongodb-enterprise.v0.9.0.clusterserviceversion.yaml#L103 in `v0.9.0` for reference

**Comment by antonlisovenko** [comment]
Thanks for the report @OchiengEd , tracking in the same CLOUDP-51461 as another CSV issue

**Comment by theburi** [comment]
This issue has been resolved.
