### ISSUE TITLE
Is it possible to make mongodb image url configurable in statefulset generated by operator

### ISSUE THREAD

**Issue by jefflee416** [mongodb/mongodb-enterprise-kubernetes#36]
Hello, I have mongodb-enterprise-operator 1.2.0 installed on openshift, I tried to deploy a replica-set mongo DB instance, operator created a statefulset for me, all good at this point.

The problem is that operator hard-coded mongodb image url: "image: quay.io/mongodb/mongodb-enterprise-database:1.2.0", and my Openshift is behind corporate firewall, I can only get image from an internal image repository.
I wanted to overwrite this image url, I tried manually edit statefulset generated by operator,  but after few seconds operator changed it back to default.

So can you make the mongodb image url configurable in operator generated statefulset?

**Comment by rodrigovalin** [comment]
Hello,

You can actually pass your own image to the Operator. This is stored in the `MONGODB_ENTERPRISE_DATABASE_IMAGE` environment variable of the Operator Pod.

Depending on how you installed the Operator you might want to edit the `values.yaml` in the Helm chart or any other mechanism you used, like modifying the yaml installation files (if you used `oc apply -f mongodb-enterprise.yaml` at the root of this project).

Just point the variable to where your actual database image is and re-install the operator.

**Comment by jefflee416** [comment]
hi Rodrigo, 
Thanks for the quick reply. Jeegar helped me out on this, I ended up with updating mongodb-enterprise.yaml with my internal image url. I am fine with this part now. 
Thanks again!
