### ISSUE TITLE
Mongos pods restart each hour

### ISSUE THREAD

**Issue by szaharici** [mongodb/mongodb-enterprise-kubernetes#4]
I have been playing with the operator and it's working well, however I noticed that mongos pods are restarted each hour. This comes from the liveliness probe `/mongodb-automation/files/probe.sh`that checks if the container uptime is less than an hour. Why is this implemented in this way ? Is there a memory leak in mongos ?

**Comment by antonlisovenko** [comment]
no, we allow the container one hour after start to download mongod/mongos binary (as network can be slow) and only then perform the check.
But there is a bug for mongoses that we need to fix, thanks for this pointing out 👍

**Comment by jamesbroadhead** [comment]
Thanks for filing! We're tracking this internally as CLOUDP-34616 (private bug tracker)

**Comment by jamesbroadhead** [comment]
Will be fixed in 0.6
