### ISSUE TITLE
Arbiter in mongo.

### ISSUE THREAD

**Issue by perdoorrajeshnayak** [mongodb/mongodb-enterprise-kubernetes#40]
Hi all,
          I have kubernates cluster  and i have created a  mongo statefulset  in that  cluster. Basically i have  3 pod, one is primary and remaining is secondary. Now i need to configure the Arbiter in mongo. How can do that?. 
         Thanks in advance.

**Comment by antonlisovenko** [comment]
hi @perdoorrajeshnayak 
There is no way to do this using Mongodb Operator - you can use Ops Manager configuration to change replica set topology.

**Comment by perdoorrajeshnayak** [comment]
Thanks Anton  for your quick reply,
how to use the  Ops Manager  in kubernates cluster as deployment or statefulset. can please provide some references. Thanks  advance.

**Comment by antonlisovenko** [comment]
You can try the [Ops Manager in Kubernetes](https://github.com/mongodb/mongodb-enterprise-kubernetes#ops-manager-object-alpha). Note, that currently it's alpha and is not recommended for production, beta may have breaking changes. Even better option is to use Cloud Manager which will allow to avoid installation hassle
