### ISSUE TITLE
namespace setting, should switch to use .Release.Namespace

### ISSUE THREAD

**Issue by realmbgl** [mongodb/mongodb-enterprise-kubernetes#44]
Currently you have the following conditional in `operator.yaml` for `namespace`.
https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/helm_chart/templates/operator.yaml#L6
```
{{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{ end }}
```

You don't have the conditional in other places, e.g https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/helm_chart/templates/roles.yaml#L91.
```
  name: {{ .Values.operator.name }}-{{ .Values.namespace }}-certs-binding
```

So if you set the following in `values.yaml` things will brake
```
namespace: none
needsCAInfrastructure=true                                # this is the default
```

Any reason you not just using `{{ .Release.namespace }}`. That would simplify things, you would not have to create the ns via kubectl, helm will create it with whatever you specify with the `--namespace` option.

```
helm install mongodb-enterprise-operator -n mdbop --namespace mongodb --repo https://...
```

**Comment by antonlisovenko** [comment]
Hi @realmbgl 

thanks for the report

I've created the CLOUDP-51481 to fix the problem. May be we'll make the `namespace` field mandatory

The reason why we don't use `helm install` or `helm upgrade` is that this complicates the workflow significantly (you need to install helm properly first) and also doesn't allow to perform smoothless upgrades of existing Operator application. Upgrade using `kubectl apply` works perfectly, so we basically recommend all the users to use helm just as a templating engine to generate yaml files.

**Comment by mmambrose** [comment]
+1 to this suggestion. We have manually modified the operator helm chart on our side to use the {{ .Release.Namespace }} pattern so that we can do multiple `helm install` onto a single cluster without changing `values.yaml` file.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
