### ISSUE TITLE
provide helm chart repository

### ISSUE THREAD

**Issue by realmbgl** [mongodb/mongodb-enterprise-kubernetes#45]
It would be great if the operator would be available via a helm chart repository. Will simplify automation.

**Comment by antonlisovenko** [comment]
hi @realmbgl 
thanks for the report

There's an internal ticket CLOUDP-31302 for the helm chart registry support, seems we failed to find time for it, I'll put this feature up for next discussion

**Comment by rodrigovalin** [comment]
We won't be providing a Helm chart for the Enterprise Operator. The supported ways of installing it are:

* Using the provided instructions
* Use operatorhub.io
* If using Openshift, use Operators/Operator Hub
