### ISSUE TITLE
OPS_MANAGER_IMAGE_REPOSITORY and OPS_MANAGER_IMAGE_PULL_POLICY env variables not set in CSV

### ISSUE THREAD

**Issue by komish** [mongodb/mongodb-enterprise-kubernetes#46]
Hi all!

Looking at the CSV on [operatorhub.io](https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/mongodb-enterprise/1.3.0/mongodb-enterprise.v1.3.0.clusterserviceversion.yaml)/Openshift's operatorhub, it seems the deployment manifest for the operator is missing the mentioned variables

```
OPS_MANAGER_IMAGE_REPOSITORY
OPS_MANAGER_IMAGE_PULL_POLICY
```

The operator fails to get started if these are not set.

These are referenced in other places such as [here](https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise.yaml#L210-L213) which supports that the CSV is what needs updating here.

**Comment by antonlisovenko** [comment]
The operatorhub has been updated: https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/mongodb-enterprise/1.3.1/mongodb-enterprise.v1.3.1.clusterserviceversion.yaml

Thanks for pointing out
