### ISSUE TITLE
Convert Sharded Cluster to Replica Set

### ISSUE THREAD

**Issue by andrii-litvinov** [mongodb/mongodb-enterprise-kubernetes#50]
After the feature of exposing replica set externally with `NodePort` was released I decided to convert my single shard sharded clusters to replica sets. My steps are:

- Remove sharded cluster `mdb` resource from k8s
- Update yaml to `ReplicaSet` configuration and change resource name from `<name>` to`<name>-0`, same as it was in replica set inside the shard, to avoid the need to deal with `pvc`s and `pv`s.
- Reapply yaml with new `ReplicaSet` configuration

All goes well except after successful redeployment replica set is unable to elect primary because of hostnames in existing configuration as they reflect old names from sharded cluster.

The way to solve it is to update `rs.config()` as described in this article https://docs.mongodb.com/manual/tutorial/change-hostnames-in-a-replica-set/ with new hostnames, but it is manual action which feels a bit hacky.

Is there a better way of doing it? Or can it maybe be supported automatically?

**Comment by andrii-litvinov** [comment]
It seems that I was confused by the `<name>-sh-external` service created by the operator. I still cannot connect to replica set from outside of the cluster when specify `replicaSet=<name>` parameter and when I connect without any parameter I randomly get connect to Primary and Secondary nodes.

**Comment by BenElgar** [comment]
Hi @andrii-litvinov. External replica set connections are not yet officially supported by the operator. The good news is that this is planned for the next release which should be happening relatively soon.

**Comment by antonlisovenko** [comment]
The Operator 1.4.0 has the support for horizons for Replica Set which is the way to provide external connectivity. 
The documentation is coming, so far the samples show how this can be configured: https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/samples/mongodb/external-connectivity/replica-set-external.yaml 
(note, that the Operator will generate CSRs with external hosts listed which need to be approved manually)

Re: converting sharded cluster to Replica set - we have plans to support types conversion but this is not planned for the nearest future.

@andrii-litvinov tell me if you are ok to close the issue

**Comment by andrii-litvinov** [comment]
@antonlisovenko sure, I am okay closing this issue. I plan to give it a try within next several days.

Regarding TLS requirement, we host all the services behind the VPN and we access mongodb inside k8s through `mongos` without any TLS. Won't we be able to access replica sets from outside the k8s cluster without TLS?

And regarding host names, we currently specify IP addresses in the connection strings. Will we be able to configure horizons with IP addresses instead of host names?

**Comment by antonlisovenko** [comment]
> Won't we be able to access replica sets from outside the k8s cluster without TLS?
Unfortunately no, horizons feature works only with TLS as it uses SANs to get the the hosts requested by the client
> Will we be able to configure horizons with IP addresses instead of host names?
Should work fine - you just need to specify these IP addresses as horizon names together with ports and make sure the traffic reaches the necessary pod

**Comment by andrii-litvinov** [comment]
@antonlisovenko thanks for the hints. I tried with IPs and got following error from the Operator:
>Certificate request for `<pod-dns-name>.svc.cluster.local` doesn't have all required domains. Please manually remove the CSR in order to proceed.

I suppose the operator only looks for DNS items from CSR, not Address. Can it be addressed somehow? Otherwise I tested replica set with DNS Horizon and it works well.

**Comment by antonlisovenko** [comment]
@andrii-litvinov this is a normal message, it means that there was TLS enabled already and the certs have been approved already, so the existing CSRs need to be removed manually and then the Operator will create new ones, then you need to approve them

**Comment by andrii-litvinov** [comment]
@antonlisovenko yes, I understand that. I mean that event when I remove the CSRs it still does not work for IPs addresses. Event if I remove the MDB and the entire namespace and recreate everything from scratch I get the message from above.

**Comment by BenElgar** [comment]
Hi @andrii-litvinov, sorry for the misunderstanding. The horizons feature as it currently stands won't work with IP addresses. The reason for this is that internally MongoDB uses Server Name Indication for split horizon support and Server Name Indication does not support IP addresses.
