### ISSUE TITLE
Readme - Documentation Update - API Keys

### ISSUE THREAD

**Issue by JSdotPY** [mongodb/mongodb-enterprise-kubernetes#52]
Based on the GitHub Documentation (Readme) the API Key that is needed for using the Ops-Manager Kubernetes Operator is the Public API Key.
https://github.com/mongodb/mongodb-enterprise-kubernetes
Under Adding Ops Manager Credentials

Starting in OpsManager 4.2.4, it is clearly stated, that the Public API Keys are deprecated and will be removed in future versions.

We are now using Programatic API Keys (according to the documentation here:https://docs.mongodb.com/kubernetes-operator/master/tutorial/create-operator-credentials/ ) - but this should be adjusted on the GitHub page as well.

**Comment by antonlisovenko** [comment]
thanks for the feedback, we'll change the Readme to include the information about Programmatic keys.
The public api keys are deprecated but will be used until next minor Ops Manager version (4.4) which will happen not very soon.
So far both public API keys and programmatic API keys can be changed interchangeably
