### ISSUE TITLE
Split horizon DNS support for MongoDB replica sets

### ISSUE THREAD

**Issue by delgod** [mongodb/mongodb-enterprise-kubernetes#53]
Hi 👋 

I see the following item in the release notes
> Split horizon DNS support for MongoDB replica sets has been added, allowing clients to connect to replica set from outside of the Kubernetes cluster.

Could you please explain how Split horizon DNS is possible in MongoDB?
Or how it was implemented in Kubernetes Operator?

**Comment by jamesbroadhead** [comment]
Well-spotted! We're working on detailed documentation for the feature, it'll be published soon.

**Comment by theburi** [comment]
@delgod Here is the documentation for External connectivity
https://docs.mongodb.com/kubernetes-operator/master/tutorial/connect-from-outside-k8s/
