### ISSUE TITLE
ReplicaSet external connectivity issues

### ISSUE THREAD

**Issue by andrii-litvinov** [mongodb/mongodb-enterprise-kubernetes#59]
I have configured ReplicaSet with Split Horizon in a following way:

```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongo-local
  namespace: <project-namespace>
spec:
  members: 2
  version: 4.2.2
  type: ReplicaSet

  opsManager:
    configMapRef:
      name: <project-name>
  credentials: <credentials>

  persistent: true

  podSpec:
    podAntiAffinityTopologyKey: kubernetes.io/hostname
    persistence: 
      multiple:    
        data:
          storageClass: local-path
        journal:
          storageClass: local-path
        logs:
          storageClass: local-path

  security:
    tls:
      enabled: true
    authentication:
      enabled: true
      modes: ["SCRAM"]

  connectivity:
    replicaSetHorizons:
      - "horizon-1": "node-2:31502"
      - "horizon-1": "node-3:31503"
```
Added following services to ensure each port is routed to correct pod:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-local-0-svc-external
  namespace: <project-namespace>
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31502
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-local-0
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-local-1-svc-external
  namespace: <project-namespace>
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31503
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongo-local-1
  sessionAffinity: None
  type: NodePort
```
And added `node-2` and `node-3` to my hosts file. When I try to connect with mongo shell all works as expected:
```bash
$ mongo mongodb://admin:admin-password@node-2:31502,node-3:31503/admin?replicaSet=mongo-local --tls --tlsCAFile kube-ca.pem
MongoDB shell version v4.2.2
connecting to: mongodb://node-2:31502,node-3:31503/admin?compressors=disabled&gssapiServiceName=mongodb&replicaSet=mongo-local
2020-01-09T16:52:08.407+0200 I  NETWORK  [js] Starting new replica set monitor for mongo-local/node-2:31502,node-3:31503
2020-01-09T16:52:08.407+0200 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to node-3:31503
2020-01-09T16:52:08.408+0200 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to node-2:31502
2020-01-09T16:52:08.425+0200 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for mongo-local is mongo-local/node-2:31502,node-3:31503
Implicit session: session { "id" : UUID("9d7d32a9-8bb7-4755-9254-56c559ac03c8") }
MongoDB server version: 4.2.2

mongo-local:PRIMARY>
```
When I try to use C# driver I get an error that driver cannot connect to the replica set:
```csharp
var settings = MongoClientSettings.FromConnectionString("mongodb://admin:admin-password@node-2:31502,node-3:31503/admin?replicaSet=mongo-local");
settings.UseTls = true;
settings.AllowInsecureTls = true;

var cursor = await new MongoClient(settings).ListDatabasesAsync();
await cursor.MoveNextAsync();

cursor.Current.Should().NotBeEmpty();
```
```
System.TimeoutException : A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "ReplicaSet", Type : "ReplicaSet", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/node-3:31503" }", EndPoint: "Unspecified/node-3:31503", State: "Disconnected", Type: "Unknown", LastUpdateTimestamp: "2020-01-09T14:40:36.8765379Z" }] }.
   at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterSeverSelctionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.StartImplicitSessionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
```
And when I try to connect with DataGrip I get following error:
```
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@7a386fe4. Client view of cluster state is {type=REPLICA_SET, servers=[{address=node-3:31503, type=UNKNOWN, state=CONNECTING}]. 
```
I am not sure what I am missing if I am missing something. I have created an issue in mongodb C# driver jira https://jira.mongodb.org/browse/CSHARP-2888, but haven't got much help there.

**Comment by antonlisovenko** [comment]
hi @andrii-litvinov 
is it possible for you to try other drivers? Python/nodejs ones should be quite easy to test and start.
It will require a bit more time for us to experiment with C# applications and we may not have enough time to try it this week.

**Comment by andrii-litvinov** [comment]
I have tried with DataGrip and it uses Java driver, I should have mentioned that explicitly. Same error. I expect other driver to have the same issue, but let me try maybe with nodejs. I am not that much familiar with neither of those.

**Comment by andrii-litvinov** [comment]
@antonlisovenko I have tried with nodejs driver and it worked fine. I still have issue connecting with C# driver and Java drivers. Do you maybe have an example how the proper Split Horizon configuration should look like including NodePort services? Maybe I did something wrong there? Or do you know if C# driver team can test it somehow? They mentioned @BenElgar in that issue, but he haven't confirmed if the configuration is correct or not.

**Comment by BenElgar** [comment]
After further investigation we believe this is due to a bug in MongoDB. This is now fixed and this fix will be released in the next versions of MongoDB 3.6, 4.0 and 4.2. For more information see here: https://jira.mongodb.org/browse/SERVER-45396

**Comment by andrii-litvinov** [comment]
MongoDB 4.2.3 was released. I have tested it and now connection works with C# driver as well, so closing the issue. Thanks!

**Comment by jamesbroadhead** [comment]
Just for future reference, the versions needed are:
3.6.17+, 
4.0.15+,
4.2.3+, 
4.4.0+ (once it's out)

**Comment by kpiyush17** [comment]
@andrii-litvinov 
I am trying to expose my Replica set outside k8s. 

>   connectivity:
    replicaSetHorizons:
      - "horizon-1": "node-2:31502"
      - "horizon-1": "node-3:31503

I wanted to ask that whether `node-2` or `node-3` are just random strings or they have to mapped somewhere?

Also, 
> And added node-2 and node-3 to my hosts file.

Is this a necessary step?

**Comment by andrii-litvinov** [comment]
@kpiyush17 those are just random strings for host names. Host names that you specify in the Horizons configurations has to be discoverable for the clients either through DNS, hosts file or any other network configuration. And <hostname>:<port> pair should resolve to concreate pod through k8s service configuration.

**Comment by kpiyush17** [comment]
> Host names that you specify in the Horizons configurations has to be discoverable for the clients either through DNS, hosts file or any other network configuration.

Can you share the hosts file?

**Comment by andrii-litvinov** [comment]
It was something like
```
192.168.1.102    node-2
192.168.1.103    node-3
```
Where 192.168.1.10x is the IP address of the k8s worker node. It's just regular hosts file and it's used only for development. In production deployment hostnames should be discoverable by client via networking. Otherwise you would have to configure hosts file for every client that needs to connect to the DB.

**Comment by kpiyush17** [comment]
@andrii-litvinov 

> Where 192.168.1.10x is the IP address of the k8s worker node.

Does this mean node should have an external IP?

> In production deployment hostnames should be discoverable by client via networking.

Can you tell me ways on how to achieve this?

**Comment by andrii-litvinov** [comment]
I think it's best for you to consult with your system administrator, SRE or DevOps guy who is responsible for networking in your company. I am not sure I can help much more, because the networking is configured differently in different companies. Try also to google `network hostname resolution` it may give you some ideas.
