### ISSUE TITLE
failed to create symbolic link '/data/journal': Permission denied

### ISSUE THREAD

**Issue by xiaozhongliu** [mongodb/mongodb-enterprise-kubernetes#60]
```
~ k get po
NAME                                           READY   STATUS             RESTARTS   AGE
mongodb-enterprise-operator-7cbd848788-bxq2f   1/1     Running            0          36h
om-db-0                                        0/1     CrashLoopBackOff   12         37m

~ k logs om-db-0
{"logType":"agent-launcher-script","contents":"Using Kubernetes CA file"}
{"logType":"agent-launcher-script","contents":"Added 2000 to /etc/passwd"}
ln: failed to create symbolic link '/data/journal': Permission denied
```

**Comment by antonlisovenko** [comment]
hi @xiaozhongliu 
can you tell which Kubernetes cluster you use? Which version of the Operator? What environment variables do you use for the operator pod?

**Comment by cpavan811** [comment]
@xiaozhongliu I too got same issue..and I resolved by using podSpec.persistence.multiple rather podSpec.persistence.single.
below is simple replicaset yaml file which uses multiple persistent volumes for data,journal and logs

---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: test
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: 4.0.0

  persistent: true
  project: my-project
  credentials: opsmanager-access
  podSpec:
    persistence:
      multiple:
        data:
          storage: 60Gi
          storageClass: local-path
        journal:
          storage: 10Gi
          storageClass: local-path
        logs:
          storage: 3Gi
          storageClass: local-path

**Comment by andrii-litvinov** [comment]
We resolved it by using multiple persistence as well, but it is weird that single persistence results in such issue.

**Comment by antonlisovenko** [comment]
Thanks for the report, and yes, it's pretty weird. In case of single persistence the single volume is mounted and the `data`, `journal` and `logs` sub folders are used there. In case of multiple persistence 3 volumes are mounted each to the folders above respectively. Basically for single persistence one subfolder in a mounted volume (`/data/journal`) is symlinked to `/journal` which is created during Dockerfile build. Our tests on AWS, Openshift and Kind work fine for this. Is there anything special in your use cases - environment, storage, permissions etc?

**Comment by andrii-litvinov** [comment]
We use cluster created by Rancher and https://github.com/rancher/local-path-provisioner for storage class. All with default configs. It reproduces on both Ubuntu VMs created in Hyper-V and bare-metal nodes.

**Comment by antonlisovenko** [comment]
Thanks @andrii-litvinov for this information!

@cpavan811  @xiaozhongliu could you please describe your environment more? Do you also you local volumes?

**Comment by cpavan811** [comment]
@antonlisovenko Yes we do use persistent volumes it's mentioned above that set to persistent:true 
We use k8s cluster spined up by rancher and rancher hosts storage class. We restored data from compose to replicaset. but we are stuck at creating admin dbuser (enabling auth and TLS)  both in operator or opsmanager.

**Comment by antonlisovenko** [comment]
@cpavan811 do you use local storages as well?

Re: admin dbuser - please create a separate issue

**Comment by AhmadAlKhaldi86** [comment]
Any Update on this issue? I am using openshift 4.3 . I have tried using multiple storage solution but still did not work

**Comment by AhmadAlKhaldi86** [comment]
> Any Update on this issue? I am using openshift 4.3 . I have tried using multiple storage solution but still did not work

@antonlisovenko

**Comment by antonlisovenko** [comment]
@AhmadAlKhaldi86 This is an indication that the volume is mounted in readonly mode. For Openshift we don't set securityContext as Openshift does this by itself though this requires the `MANAGED_SECURITY_CONTEXT` config property to be set to `true`. What is the config you are creating? Do you use a static or dynamic volume binding?

**Comment by xiaozhongliu** [comment]
> We resolved it by using multiple persistence as well, but it is weird that single persistence results in such issue.

I confirm I have exactly the same situation. It works with multiple volumes, but not with single volume.
@antonlisovenko I build the cluster with the latest rancher, and the volumes are provisioned via rancher/local-path-provisioner.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
