### ISSUE TITLE
Provide a way to use adminCommand setParameter in MongoDB resource

### ISSUE THREAD

**Issue by andrii-litvinov** [mongodb/mongodb-enterprise-kubernetes#67]
After upgrade to MongoDB 4.2.3 we have to set `internalQueryMaxAddToSetBytes` parameter in order to let some of our aggregations to work correctly. Is there a way to set it in the yaml instead of Cloud Manager? Also such feature would be useful to manage oplog size and some other parameters, as doing it manually from Cloud Manager is not very convenient when there are many clusters to manage. And parameters in cloud manager get deleted from Cloud Manager project if MongoDB resource gets deleted and recreated in k8s cluster.

Also regarding Split Horizons feature, when I set parameter in Cloud Manger it decided to remove horizons from mongodb deployement for some reason. So I have to trigger reconciliation somehow. Is there a way to prevent Cloud Manager from removing horizon configuration?

**Comment by antonlisovenko** [comment]
Hi Andrii

the configuration for Mongodb params from CR spec is planned to be done but not very soon - approximately eof April.

**Comment by theburi** [comment]
Hi Andrii
You could set it using OpsManager in Advanced cluster configuration setParameter (our using API)
We are going to add all these Options to our CRD.
Please vote: https://feedback.mongodb.com/forums/924355-ops-tools/suggestions/39618988-support-any-mongodb-configuration-option-in-mongod

**Comment by rodrigovalin** [comment]
It seems we should be able to close this for now. Please reopen or create a new issue if the problem persist or you need more help with it.
