### ISSUE TITLE
Unable to Connect to MongoDB with ReplicaSet Flag

### ISSUE THREAD

**Issue by junlouiegonzales** [mongodb/mongodb-enterprise-kubernetes#68]
Hello guys I'm new with this tool and to the kubernetes environment. 
I'm just trying to connect to MongoDB server using shell but I always get this error 
![image](https://user-images.githubusercontent.com/20350350/73802049-53676280-47f7-11ea-9e52-754f29d68f12.png)

And without the "replicaSet" flag It's randomly connected to a primary and secondary replica set.
![image](https://user-images.githubusercontent.com/20350350/73802177-c375e880-47f7-11ea-9fcb-569f09ccf4dc.png)

![image](https://user-images.githubusercontent.com/20350350/73802229-f9b36800-47f7-11ea-9a0a-c6e04fab89c0.png)
![image](https://user-images.githubusercontent.com/20350350/73802281-236c8f00-47f8-11ea-88c7-646cc074a89f.png)

**Comment by andrii-litvinov** [comment]
You have to use Split Horizons feature of MongoDB in order to connect to replica set externally. You can find some more details here https://github.com/mongodb/mongodb-enterprise-kubernetes/issues/59.

**Comment by junlouiegonzales** [comment]
Where did you get the .pem file or how to generate that?

**Comment by junlouiegonzales** [comment]
![image](https://user-images.githubusercontent.com/20350350/74219130-e831fa80-4ce6-11ea-83ab-1ed2d672a809.png)

![Uploading image.png…]()

I don't know if I miss something with the configuration :(

**Comment by andrii-litvinov** [comment]
That's the k8s Certificate Authority that was used to approve Certificate Signing Request (CSR). I use Rancher and on my nodes it's located in `/etc/kubernetes/ssl/kube-ca.pem`.

**Comment by junlouiegonzales** [comment]
I just encounter the same problem after configuring Split Horizon

**Comment by andrii-litvinov** [comment]
You have to configure services so that each port forwards connection to concrete pod. And they have to match in horizons configuration.

**Comment by rodrigovalin** [comment]
@junlouiegonzales I'm closing this issue for now, please feel free to re-open it if needed, or to create a new issue.
