### ISSUE TITLE
Enhance Project/Credentials objects to capture Automation Agent-to-Ops Manager SSL Settings

### ISSUE THREAD

**Issue by ron1** [mongodb/mongodb-enterprise-kubernetes#7]
The MongoDB Enterprise Operator Project ConfigMap and/or Credentials Secret should be enhanced to capture Automation Agent-to-Ops Manager SSL Settings as described here: https://docs.opsmanager.mongodb.com/current/reference/automation-agent/#mms-ssl-settings.

Currently, when the Automation Agent must use SSL to connect with Ops Manager, the connection may fail because the SSL configuration defaults are inadequate. In this case, X509 errors are reported, the connection fails, and the MongoDB cluster is never provisioned.

**Comment by antonlisovenko** [comment]
Sorry for late response, 
we are currently starting works on SSL support - will also work on support for SSL communication between Automation Agent and Ops Manager. Tracking this in internal ticket
