### ISSUE TITLE
sync mongodb-enterprise operator available in openshift with upstream

### ISSUE THREAD

**Issue by komish** [mongodb/mongodb-enterprise-kubernetes#70]
Hi all! -- There are a few changes that might be missing in the version of the operator available in openshift. May be related to issues: #37, #46, and potentially #33. 

Version available in openshift's embedded operator hub is 1.2.4 (compared to 1.4.2 available in [upstream-community-operators](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/mongodb-enterprise/1.4.2).

Went to the referenced slack channel in the README.md for this project but it looks like the operator channels have been migrated to the mongodb community forums. I didn't see any discussion there under the kubernetes-operator [tag](https://community.mongodb.com/tags/kubernetes-operator) so I figured I'd follow back up here.

**Comment by rodrigovalin** [comment]
Hello,

Thanks for reporting. Version 1.4.2 of the operator has been pushed to Openshift. We just finished setting up the internal Openshift 4.3 testing cluster that will give us more visibility on the overall experience with installing and using the operator.

I will report my finding regarding the reported issues in the next few days.

**Comment by komish** [comment]
Understood, thanks @rodrigovalin! I'll keep a look out in the openshift marketplace for the update as well as further updates here.

**Comment by srinivma1** [comment]
Any updates on this. When can we expect the 1.4.2 version of operator to be rolled out in OCP v4.3 cluster?

**Comment by antonlisovenko** [comment]
Hi
The community operators has the previous 1.4.3 version available, we are trying to merge the 1.4.4 there
The operatorhub constantly gives an error when we try to upload the metadata resources, we'll try to solve this soon. You can use Openshift Container catalog images still which are up-to-date

**Comment by theburi** [comment]
This issue has been addressed. We are now at version 1.6
Usually, we get a few days to get each new version of Operator certified with OpenShift, but sometimes it may take longer.
This issue should be resolved now.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
