### ISSUE TITLE
Error reading or creating project in Ops Manager

### ISSUE THREAD

**Issue by g3gurung** [mongodb/mongodb-enterprise-kubernetes#71]
`Status:
  Last Transition:  2020-02-18T09:17:22Z
  Message:          Error reading or creating project in Ops Manager: organization with id xxxxxxxxxxxx not found: Status: 401 (Unauthorized), Detail: You are not authorized for this resource.
  Phase:            Failed
  Type:             
  Version:          
`

I have cloud manager setup already. And also provided orgId and projectName with the cloud manager base url in config. Also for the secrets I have created the API key in cloud manager and set it to k8's secret as per instruction. But still I am getting the above error.

For whitelisting I created an egress IP in azure cloud and set it for my k8 cluster and used it for generating API key.

**Comment by antonlisovenko** [comment]
hi @g3gurung 

Check the IPs of the Kubernetes worker nodes your cluster is running and add them to whitelist.
The Operator pod may be running on any of those nodes so adding only one may stop working in future

If you use `kubectl` then the following command will give you external IPs:
`kubectl get nodes -o wide`

If this doesn't help then check the credentials you are using - you can make the curl request to public API, check this docs for reference: https://docs.cloudmanager.mongodb.com/reference/api/organizations/organization-get-all/

**Comment by g3gurung** [comment]
HI @antonlisovenko 
I did try the public API request with curl from inside the kubernetes mongo operator pod/container. I am getting this expected responses which seems to be fine.

**curl --user '{PUBLIC-KEY}:{PRIVATE-KEY}' --digest \
 --header 'Accept: application/json' \
 --include \
 --request GET "https://cloud.mongodb.com/api/public/v1.0/groups?pretty=true"**

`HTTP/1.1 401 Unauthorized
Date: Tue, 18 Feb 2020 10:28:24 GMT
WWW-Authenticate: Digest realm="MMS Public API", domain="", nonce="nOeC3jIcq5jBcuafhQccsB2eLq79Kjhs", algorithm=MD5, qop="auth", stale=false
Content-Type: application/json
Content-Length: 106

HTTP/1.1 200 OK
Date: Tue, 18 Feb 2020 10:28:24 GMT
X-MongoDB-Service-Version: gitHash=a21e44a00ef613d177dd238022494451e971ce15; versionString=v20200128
Content-Type: application/json
Strict-Transport-Security: max-age=300
Vary: Accept-Encoding, User-Agent
Content-Length: 734
`

**Comment by gauravtaneja1984** [comment]
> hi @g3gurung
> 
> Check the IPs of the Kubernetes worker nodes your cluster is running and add them to whitelist.
> The Operator pod may be running on any of those nodes so adding only one may stop working in future
> 
> If you use `kubectl` then the following command will give you external IPs:
> `kubectl get nodes -o wide`
> 
> If this doesn't help then check the credentials you are using - you can make the curl request to public API, check this docs for reference: https://docs.cloudmanager.mongodb.com/reference/api/organizations/organization-get-all/

I am also facing similar issue,could you please help me out.
