### ISSUE TITLE
Generate API keys on installation of ops manager

### ISSUE THREAD

**Issue by dimitarKiryakov** [mongodb/mongodb-enterprise-kubernetes#79]
We want to automate the process of installation of the ops manager. 
Is there a way to create the API keys without the UI? 
Something like the initial user is set up(with a secret). The idea is that we want to remove the manual steps of going to UI, create API keys and then you can use the Ops Manager API.

**Comment by antonlisovenko** [comment]
Hi @dimitarKiryakov 

the global admin is created by the Operator on start - his credentials are saved into the secret `<om-name>-admin-key`. So you can use these credentials for further interaction with OM API. Just make sure these credentials are not used for normal MongoDB resources - the non-admin users need to be created for this

**Comment by dimitarKiryakov** [comment]
@antonlisovenko Thanks
