### ISSUE TITLE
Continue supporting minKubeVersion 1.11.0 and therefore OCP 3.11 in latest operator version

### ISSUE THREAD

**Issue by ron1** [mongodb/mongodb-enterprise-kubernetes#82]
Version 1.4.0 of the operator increased minKubeVersion from 1.11.0 to 1.13.0. This eliminates OCP 3.11 as a target platform for the latest operator version. Is it possible to continue support for Kubernetes 1.11/OCP 3.11 in the latest version of the operator since OCP 3.11 will be supported by Red Hat until June 2022 and since the move from OCP 3.11 to OCP 4.x is a rip-and-replace activity.

**Comment by theburi** [comment]
Hi. Our current plan to support OpenShift 3.11 until the end of its Full support period Jun 2020. Then only security features will be provided as OpenShift enters Maintainance period. This extends only to OpenShift 3.11 and not Kubernetes 1.11.

**Comment by rodrigovalin** [comment]
Closing as solved.

**Comment by jamesbroadhead** [comment]
For future reference, we intend to support OpenShift in Operator 1.7.0 (not yet released) until the Openshift 3.11 EOL, which has been moved to July 2021. 
This will be published in the Operator documentation once 1.7.0 has been released

References: 
https://access.redhat.com/support/policy/updates/openshift_noncurrent
https://access.redhat.com/articles/4994921

**Comment by ron1** [comment]
Great! Thanks.
