### ISSUE TITLE
Exposing MongoDB outside Kubernetes using proxy

### ISSUE THREAD

**Issue by kpiyush17** [mongodb/mongodb-enterprise-kubernetes#83]
Hi,

I am trying to expose MongoDB outside Kubernetes using Envoy. In the Envoy, I have added the rule to always route traffic to the headless service created by the MongoDB operator. 

Envoy config:
```
  routes:
       - match:
              prefix: "/"
          route:
              cluster: mongodb
```  
```
clusters:
      - name: mongodb
        connect_timeout: 0.5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        http2_protocol_options: {}
        load_assignment:
          cluster_name: mongodb
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: dev-mongo-svc.mongodb.svc.cluster.local
                    port_value: 27017
```

Also, I am terminating SSL on Envoy only. When trying to connect to the url of proxy with SSL certs, I am getting the following error:
```
mongo --host <host_name>:443 --tls --tlsCAFile bundle_ca.crt --tlsCertificateKeyFile client-full.pem --authenticationMechanism MONGODB-X509
MongoDB shell version v4.2.3
connecting to: mongodb://<host_name>:443/?authMechanism=MONGODB-X509&compressors=disabled&gssapiServiceName=mongodb
2020-04-08T18:46:59.795+0530 I  NETWORK  [js] recv(): message msgLen 1347703880 is invalid. Min 16 Max: 48000000
2020-04-08T18:46:59.795+0530 I  NETWORK  [js] DBClientConnection failed to receive message from lr-dev-db.div4.dev:443 - ProtocolError: recv(): message msgLen 1347703880 is invalid. Min 16 Max: 48000000
2020-04-08T18:46:59.796+0530 E  QUERY    [js] Error: network error while attempting to run command 'isMaster' on host '<host_name>:443'  :
connect@src/mongo/shell/mongo.js:341:17
@(connect):3:6
2020-04-08T18:46:59.802+0530 F  -        [main] exception: connect failed
2020-04-08T18:46:59.802+0530 E  -        [main] exiting with code 1
```
From the error, I can understand that it is trying to find mongod in envoy pods only, right? Is there a way to solve this or a different way to expose MongoDB?

**Comment by antonlisovenko** [comment]
hi @kpiyush17 

sorry for late response
Are you using replica sets? For replica sets the way to enable external access is using [split horizons](https://docs.mongodb.com/kubernetes-operator/stable/tutorial/connect-from-outside-k8s/). We haven't dealt with envoy much so may be you could try to use the simpler approach (NodePorts as described in the docs) and then try Envoy after confirming that connectivity via NodePorts works?

**Comment by kpiyush17** [comment]
@antonlisovenko 

Yes, we are using replica sets. We can't use NodePort because we need to access the database from multiple regions those regions are not in same VPC. Also, our cluster nodes do not have External IP assigned to them. That's why we thought of using a proxy to the exposing part.

**Comment by antonlisovenko** [comment]
@kpiyush17 

Have you enabled split horizons for your replica set?

**Comment by kpiyush17** [comment]
@antonlisovenko 

No, we haven't enabled split horizons.

**Comment by theburi** [comment]
@kpiyush17 MongoDB Replicaset is using WireTiger Protocol over TCP. HTTP proxies would not be properly redirecting traffic to each member.
Best was it to expose each MongoDB node with ingress so it will map 1:1 to each node and configure Split Horizon. TLS will be required for MongoDB to validate incoming traffic and determine correct responses based on its origin.  
https://docs.mongodb.com/kubernetes-operator/master/tutorial/connect-from-outside-k8s/

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
