### ISSUE TITLE
SCRAM-SHA-1 support

### ISSUE THREAD

**Issue by NickSchleicher** [mongodb/mongodb-enterprise-kubernetes#84]
Currently upgrading to 1.4, previously with 1.1 it was possible to still use SCRAM-SHA-1

With version 1.4.4, I only see `modes: ["SCRAM"]`? Can I still use SCRAM-SHA-1 somehow or do I have to upgrade my db users?

**Comment by antonlisovenko** [comment]
hi @NickSchleicher 

sorry for late response.
Current logic is that the Scram-sha version is deduced from the mongodb version: for all versions <= 3.6 Mongodb the Operator will set scram-sha-1 and  for all versions >= 4.0 it will set scram-sha-256
