### ISSUE TITLE
Image name must not include deployment name

### ISSUE THREAD

**Issue by jstudler** [mongodb/mongodb-enterprise-kubernetes#85]
Hi,

In the Operator helm template, the image name is set to the Operator deployment name. Deploying multiple operators in the same namespace would therefore not be possible.

https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/e6af238e9b3c1623c1e3dca6c5d2902cced7136e/helm_chart/templates/operator.yaml#L32

Please adjust this line to look as follows:
`        image: {{ .Values.registry.repository }}/mongodb-enterprise-operator:{{ .Values.operator.version }}
`
or add the image name as helm configuration value.

Best regards, Joel

**Comment by antonlisovenko** [comment]
Hi @jstudler 

what's the use case for deploying multiple Operators in one namespace?

**Comment by jstudler** [comment]
Hi @antonlisovenko 

Creating one namespace for management where all Operators are deployed. Eeach Operator would manage another namespace. This is documented here https://docs.mongodb.com/kubernetes-operator/stable/tutorial/plan-k8s-operator-install/#k8s-op-short-deployment-scopes under "Operator in Different Namespace Than Resources".

Regardless of this question the image name should not be determined by the deployment name. The value operator.name is currently useless in this helm chart unless you use the default value. If you deploy the Operator with operator.name set to "my-operator" the pod will not be scheduled.

**Comment by antonlisovenko** [comment]
thanks @jstudler for this information.
You are right that the operator image name shouldn't depend on on the deployment name. We plan to fix this soon.
So far can you fix this in the helm chart copy you have? We haven't experimented with multiple Operators in one namespace watching different namespaces - this is an interesting use case. Have you succeeded in this?

**Comment by jstudler** [comment]
hi @antonlisovenko 
Thanks a lot for fixing it. Yes, i have changed this line as proposed and it was possible to deploy multiple Operators in one namespace.
However as it does not seem to be well supported I did not go further with this scenario having multiple MongoDB Operators in one Namespace. See Case 00649289.

**Comment by antonlisovenko** [comment]
the issue was fixed and released, closing
