### ISSUE TITLE
Failed to create/update (Ops Manager reconciliation phase)

### ISSUE THREAD

**Issue by kpiyush17** [mongodb/mongodb-enterprise-kubernetes#86]
Hi,

I had deployed a replicaset on the cluster. After that, I deleted that replicaset and tried to deploy Standalone. But I am getting below error.
```
message: 'Failed to create/update (Ops Manager reconciliation phase): Some agents
    failed to register or the Operator is using the wrong hostnames for the pods.
    Make sure the ''spec.clusterDomain'' is set if it''s different from the default
    Kubernetes cluster name (''cluster.local'') '
```
I  have not configured any custom domain for the cluster. 
Due to this, the Mongo pods readiness probe is failing and the pods are getting continuously terminated and restarted. Not sure how to debug and solve this.

Thanks

**Comment by antonlisovenko** [comment]
hi @kpiyush17 

Do you have config files for the replica set you had before and the new standalone resource?
Can you please provide the operator logs?
Also it may make sense to start operator with `OPERATOR_ENV=dev` environment to increase logging level to `debug` and see more information in the logs.

**Comment by kpiyush17** [comment]
@antonlisovenko 

Sorry, I don't have the logs right now. The error persist for a long time so I have to delete the namespace basically and after that, it working fine right now. 
Although, I wasn't able to come up with the possible reasons for this issue. One thing to notice is that it happens most of the time when I delete a MongoDB resource and try to re-deploy it.

**Comment by antonlisovenko** [comment]
thanks for the update @kpiyush17 

so do you mean your standalone had the same name as the replica set?

**Comment by kpiyush17** [comment]
@antonlisovenko 

Yes, the name was the same.

**Comment by antonlisovenko** [comment]
getting back to this issue.
Ops Manager doesn't cleanup some information about agents registered right after the deployment is removed - it may take some time for it to disappear. So creating the resource with the same name right after removal may fall and will get fixed automatically eventually. So the best would be to either wait for some time or name the new resource different way.
