### ISSUE TITLE
Document that mongodb-enterprise.yaml may need to include env var IMAGE_PULL_SECRETS for some registries

### ISSUE THREAD

**Issue by ron1** [mongodb/mongodb-enterprise-kubernetes#9]
If mongodb images are stored in a private registry, then mongodb-enterprise.yaml mayl need to include environment variable IMAGE_PULL_SECRETS as is already done for the Helm Chart (see https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/1d00e0da57f2d9f6ce4c4cda9f41cfaa95df4998/helm_chart/templates/operator.yaml#L48).

The current operator behavior on OpenShift when the mongodb images are pulled from the local registry seems incorrect. OpenShift by default automatically handles the assignment of image pull secrets when using a service account to pull images from the local registry. However, the 0.6 operator breaks this behavior because it seems to interpret a missing or empty IMAGE_PULL_SECRETS environment variable literally. As a result, the StatefulSet created by the operator has an empty imagePullSecrets value rather than a missing value. Again, in the case where the property was missing entirely from the StatefulSet, OpenShift would have handled that gracefully. The current work-around is to create the mongodb-enterprise-operator ServiceAccount separate from the Deployment. Then, after the ServiceAccount is created, copy its corresponding dockercfg Secret name as the value of environment variable IMAGE_PULL_SECRETS added to file mongodb-enterprise.yaml.

**Comment by antonlisovenko** [comment]
Seems we shouldn't initialize the `ImagePullSecrets` at all if env variable doesn't exist. Makes sense, filed a ticket for this, thanks for the feedback!

**Comment by jamesbroadhead** [comment]
Tracking internally as https://jira.mongodb.org/browse/CLOUDP-37663

**Comment by antonlisovenko** [comment]
This issue is fixed and will appear in next release (0.8)
