### ISSUE TITLE
MongoDBOpsManager - spec.applicationDatabase.members cannot be less than 3

### ISSUE THREAD

**Issue by bergkvist** [mongodb/mongodb-enterprise-kubernetes#91]
## Is there a reason for not allowing less than 3 members?
When testing things out in minikube or on a single node server, spinning up 3 of these instances feel rather overkill.

**Comment by antonlisovenko** [comment]
It's the requirement of the Ops Manager server. It won't start if application database has fewer members
Try decreasing the memory for replica set members for the app db
