### ISSUE TITLE
Unable to connect to instance externally using GKE & CloudManager

### ISSUE THREAD

**Issue by mmambrose** [mongodb/mongodb-enterprise-kubernetes#92]
We followed the documentation to deploy the MongoDB kubernetes operator, and deployed both standalone and replicaset instance but unable to connect to either. 

Adding `exposedExternally: true` to the standalone, still were not able to connect externally to the instance using Node IP addresses (since GKE does not support ExernalDNS), failed connection. 

For replicaset, since GKE does not support ExternalDNS, tried using replicaSetHorizons with External IPs, but that also did not allow connection. 

So the question is - how to connect to mongo instance with IP addresses (externally), since we do not have ExternalDNS available on GKE.

**Comment by nerdeveloper** [comment]
> We followed the documentation to deploy the MongoDB kubernetes operator, and deployed both standalone and replicaset instance but unable to connect to either.
> 
> Adding `exposedExternally: true` to the standalone, still were not able to connect externally to the instance using Node IP addresses (since GKE does not support ExernalDNS), failed connection.
> 
> For replicaset, since GKE does not support ExternalDNS, tried using replicaSetHorizons with External IPs, but that also did not allow connection.
> 
> So the question is - how to connect to mongo instance with IP addresses (externally), since we do not have ExternalDNS available on GKE.

Hello, I would love to help you out. GKE support external DNS, I personally use it. You need to create your DNS first on Google Cloud DNS, then use this link below to deploy it(RBAC enabled)

https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/gke.md#manifest-for-clusters-with-rbac-enabled

Without RBAC, use this: 
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/gke.md#manifest-for-clusters-without-rbac-enabled

The second thing is External DNS support services and ingress, meaning you might probably have to create the A name record for the replicaSetHorizons manually

expose each svc of the MongoDB as a load balancer. you will have something like this
```bash
NAME                              TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)           AGE
mongodb-replicaset-operator-0     LoadBalancer   10.245.81.226    44.144.142.92   27017:31550/TCP   88d
mongodb-replicaset-operator-1     LoadBalancer   10.245.13.155    56.33.251.2     27017:31735/TCP   88d
mongodb-replicaset-operator-2     LoadBalancer   10.245.77.194    23.20.74.100   27017:31833/TCP   88d
```

Create your configuration for a replica set to look like this or something similar
```bash
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:

  name: mongodb-replicaset-operator

  namespace: mongodb

spec:

  members: 3

  version: 4.2.2

  opsManager:
    configMapRef:

      name: mongodb-config

            # Must match metadata.name in ConfigMap file

  credentials: mycredentials
  security:
  
    authentication:
      enabled: true
      modes: ["SCRAM"] # Valid authentication modes are "SCRAM' and "X509"

      # Optional field - ignoreUnknownUsers
      # A value of true means that any users not configured via the Operator or the Ops Manager or Cloud Manager UI
      # will not be altered in any way

      # If you need to manage MongoDB users directly via the mongods, set this value to true
      ignoreUnknownUsers: true # default value false
    tls:
      enabled: true
  connectivity:
    replicaSetHorizons:
      - "mongo-kubernetes": "mongo-0.example.io:27017"
      - "mongo-kubernetes": "mongo-1.example.io:27017"
      - "mongo-kubernetes": "mongo-2.example.io:27017"

  type: ReplicaSet
  persistent: true
```

Then create an A record to point to each of the three external IP, 

for example, mongo-0.example.io will point to 44.144.142.92 (A record)

**Comment by rodrigovalin** [comment]
Hello @mmambrose 

We have documented the process to connect to the Mongodb servers from outside the Kubernetes clusters in here: https://docs.mongodb.com/kubernetes-operator/master/tutorial/connect-from-outside-k8s/

Please let me know if this helps.

**Comment by jamesbroadhead** [comment]
In order to help us manage issues and requests we have switched from GitHub Issues to the [MongoDB Support Center](https://support.mongodb.com/). Please use your Enterprise support account to raise your requests. 

If this issue is still affecting you, please open a [Support Case](https://support.mongodb.com/) or for non-blocking issues, you can make a [Feature Request](https://feedback.mongodb.com/forums/924355-ops-tools)
