### ISSUE TITLE
Errors in the operator code

### ISSUE THREAD

**Issue by desourav** [mongodb/mongodb-enterprise-kubernetes#93]
Following are the errors that I had to workaround to get the mongo operator working :  

1. The tag 1.5.0 doesn't work. I had to resolve to 1.4.5.
```
Events:
  Type     Reason     Age               From                    Message
  ----     ------     ----              ----                    -------
  Normal   Scheduled  <unknown>         default-scheduler       Successfully assigned mongodb/enterprise-operator-577c5dd474-s9xl6 to 10.188.246.44
  Normal   BackOff    23s               kubelet, 10.188.246.44  Back-off pulling image "registry.connect.redhat.com/mongodb/enterprise-operator:1.5.0"
  Warning  Failed     23s               kubelet, 10.188.246.44  Error: ImagePullBackOff
  Normal   Pulling    9s (x2 over 24s)  kubelet, 10.188.246.44  Pulling image "registry.connect.redhat.com/mongodb/enterprise-operator:1.5.0"
  Warning  Failed     8s (x2 over 24s)  kubelet, 10.188.246.44  Failed to pull image "registry.connect.redhat.com/mongodb/enterprise-operator:1.5.0": rpc error: code = Unknown desc = Error reading manifest 1.5.0 in registry.connect.redhat.com/mongodb/enterprise-operator: manifest unknown: manifest unknown
  Warning  Failed     8s (x2 over 24s)  kubelet, 10.188.246.44  Error: ErrImagePull
```

2. The environment variable **APP_DB_IMAGE_REPOSITORY** is wrongly named in the reconciliation logic. When I try to create an Ops manager it fails.
```
"error","ts":1588112708.1737993,"caller":"operator/common_controller.go:309","msg":"Failed to reconcile Ops Manager: APP_DB_IMAGE_REPOSITORY environment variable is not set!","OpsManager":"mongodb/ops-manager"
```

 I had to edit the deployment for the operator (change env variable name of **APPDB_IMAGE_REPOSITORY**)

https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/mongodb-enterprise-openshift.yaml/#L228

3. This is more of the tweak in the code. The steps involve pods that wait for `pvc`s to be created. I understand the `pvc`s are not readily available, but once they are, the pod takes a long time to retry. Sometimes pvc is available after 8 mins, but the pod event doesn't show any activity for the next 20 mins. I think there is a way to retry more frequently.

**Comment by antonlisovenko** [comment]
Hi @desourav 
thanks for your report.
We had an error in our configuration scripts in 1.5.0 tag (master was OK) - this is fixed now.

About 3)  - would be great to get more details about the problem. The Operator doesn't handle Pod/ PVC provisioning - it's done by Kubernetes based on StatefulSet spec the Operator pushes.

**Comment by antonlisovenko** [comment]
hi @desourav do you still have this issue?
