### ISSUE TITLE
MongoDB ReplicaSet TLS: Error when using custom CA

### ISSUE THREAD

**Issue by mrbq** [mongodb/mongodb-enterprise-kubernetes#94]
I am using a custom CA to sign the MongoDB ReplicaSet cluster members certificates, the configuration is correct:

```
oc describe secret oplog-db-cert
Name:         oplog-db-cert
Namespace:    mongodb
Labels:       <none>
Annotations:
Type:         Opaque

Data
====
oplog-db-1-pem:  1545 bytes
oplog-db-2-pem:  1545 bytes
oplog-db-0-pem:  1545 bytes`
```

And the custom CA configmap has been created:

```
Name:         custom-ca
Namespace:    mongodb
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","data":{"ca-pem":"...
Data
====
ca-pem:
```

But the operator MongoDB is in Failed state:

```
  Message:          The secret object 'oplog-db-cert' does not contain all the certificates needed.Required: 3, contains: 0
```

**Comment by chatton** [comment]
Hi @mrbq 

This configuration looks correct,

Does every entry in the `oplog-db-cert` secret contain both the certificate and a private key?

**Comment by mrivasxvale** [comment]
Hello @chatton,

No, each entry only contains the public key, Should I create a pem with the private and public key?

**Comment by mrbq** [comment]
Hi @chatton ,

No, should the "oplog-db-<X>-pem" contain both? If so, my bad I only included the public key.

**Comment by chatton** [comment]
Hi @mrbq 

Yes each entry should also include the private key

**Comment by mrbq** [comment]
Hi @chatton ,

Thank you, with that change the MongoDB is deployed but it is stuck in a "Reconciling" state:

```
 Failed to create/update (Ops Manager reconciliation phase): automation agents haven't reached READY state during defined interval
```

**Comment by mrbq** [comment]
The certificates I was using were not being generated properly

**Comment by Ruiwwwang** [comment]
I am referring following guide to generate pem files.  still encounter "does not contain all the certificates needed"
https://mydbops.wordpress.com/2020/05/02/securing-mongodb-cluster-with-tls-ssl/

And I have included both crt and key in pem file
cat mongod0.key mongod0.crt > mongod0-pem
cat mongod1.key mongod1.crt > mongod1-pem
cat mongod2.key mongod2.crt > mongod2-pem
cat ca.key ca.crt > ca-pem

kubectl create secret generic my-replica-set-cert --from-file=mongod0-pem --from-file=mongod1-pem --from-file=mongod2-pem
kubectl create configmap custom-ca --from-file=ca-pem

====
still encounter 
message: >-
    The secret object 'my-replica-set-cert' does not contain all the
    certificates needed.Required: 3, contains: 0

====
anybody can give instruction on it?  Thanks a lot.

**Comment by mrbq** [comment]
Have you checked that both private and public keys are included?

**Comment by Ruiwwwang** [comment]
yes， I have checked.  Following is part of my pem file for each replica node.  

`NYrkDniwCHXpr6lAfg/nbTXsOpcM9rWnTIUGb4KI30/itz3vB/BAr9leDj2p4FKs
5kM8anIVzaRU10bNoc8wtH0b2QT8n7GepNGP7ZV3az5IM9FlmQRnmggOJ3qB27Cw
2trK1DHb/6W/F2Q2fQVNn9+8cQDNGwW0uzOW3cpaDXta+nS2CkvYynLlVLe+/roq
edYRBlMG4ZHJpHgxVXMiAmg3eaPoOGxTcV8lN9P1AoIBACVbNZ3iMRik6ISnUC7/
dd4jWfsqYc7Gg9L4as4PAFQDmcZa6CxxCQDpIjYm4p7jXicrf7K21EnedIV0Sv26
aWSxC6gr4gutOC70QzVJma2V/jI9F2MyMnjy1qQlNWo9WIHIi8l7g4BG2aoAiKcw
Z3ue9VV6Pr1u8LJ4eMWes09ltFQD8xf7IYnhL3CHQMcCyK26+kkYSKJZ2pufiwEs
jtEMKios3P4ssqBX0QtbH7LWdgF7kaI8++c7AKvRp2EJHiQOxrTDDuNnsIyTikIG
jQJ8KNAMB0GW28ohQmtrDKmVCPuplNEVv/Wcf8kOjNqpkBfntSg/q2W38DJnpJNd
/0UCggEABkcBhaXTZBNzKWA8OlQEna+k/nWqPANhjU8taIqkcagtgkp0GZzZxffy
ZRQG6UEEGHE44hVjyd1XJJELNxa+ZLCZiho4IdCMFqxXz9qEFieK9UbeiFfxPKHk
BKYFOaatHFeqJAEjeyK2zLlKEDGNjTrpZfHvwseUAVz14QzyGtH+khVpgRQH1cN8
XQNGjNazTqZgNcuCQ8tRV5x8221bWBkSyTA4evGm4L4fI2b7g3g6oz9IgbqRdFRX
2WV1OushWJv+hYC0DIZVGToMNpzxkAkrPDDY9NJHxYiX6S/hsJ2in/rGn1bYBYab
xS2fQ6AdkPchV1o4MpFTAoRi8Z6BKw==
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIID6DCCA1ECCQCAket6q3PgEDANBgkqhkiG9w0BAQUFADB6MQswCQYDVQQGEwJD
TjELMAkGA1UECAwCTkIxCzAJBgNVBAcMAk5CMQwwCgYDVQQKDANJQk0xDTALBgNV
BAsMBENBRVMxEjAQBgNVBAMMCWNhLXNlcnZlcjEgMB4GCSqGSIb3DQEJARYRcm9v
dGNhQHVzLmlibS5jb20wHhcNMjAxMTI2MTM1MzUzWhcNMjAxMjI2MTM1MzUzWjBz
MQswCQYDVQQGEwJ1czELMAkGA1UECAwCbnkxCzAJBgNVBAcMAm55MQwwCgYDVQQK
DANpYm0xDDAKBgNVBAsMA2diczEZMBcGA1UEAwwQbXktcmVwbGljYS1zZXQtMDET`
