### ISSUE TITLE
Service Account not created on Openshift: mongodb-enterprise-database-pods

### ISSUE THREAD

**Issue by mrethers** [mongodb/mongodb-enterprise-kubernetes#97]
Openshift 4.2
Operator 1.4.5

mongodb-enterprise-appdb and mongodb-enterprise-operator are created automatically but not mongodb-enterprise-database-pods when installing the operator from the console.

This prevents MongoDB CRs to be created. Workaround is to manually create the service account and give it scc privileged (see my other open issue for the scc)

Cheers

**Comment by antonlisovenko** [comment]
hi @mrethers 

which console do you mean?

**Comment by LouisPlisso** [comment]
@rodrigovalin could you help on this?

**Comment by rodrigovalin** [comment]
Hello @mrethers and thanks for the report.

I think you refer to the Operator's console on your Openshift cluster.

If that's the case then yes, the `mongodb-enterprise-database-pods` is not defined in there and it should, I have created an internal ticket to track this fix from our side.

Thanks

**Comment by mrethers** [comment]
That's correct, the Openshift GUI. For non-expert Openshift, it's the kind
of the go-to way install operators. After I created it manually, everything
went smoothly.

Thanks for the awesome work though
