### ISSUE TITLE
Crds.yml giving error while using the latest code

### ISSUE THREAD

**Issue by Techshubh** [mongodb/mongodb-enterprise-kubernetes#98]
when the apply the crds.yml file with latest code . it shows following error

clusterrole.rbac.authorization.k8s.io/mongodb-enterprise-operator-mongodb-webhook configured
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apiextensions.k8s.io/v1beta1\",\"kind\":\"CustomResourceDefinition\",\"metadata\":{\"annotations\":{},\"name\":\"mongodb.mongodb.com\",\"namespace\":\"\"},\"spec\":{\"additionalPrinterColumns\":[{\"JSONPath\":\".spec.type\",\"description\":\"The type of MongoDB deployment. One of 'ReplicaSet', 'ShardedCluster' and 'Standalone'.\",\"name\":\"Type\",\"type\":\"string\"},{\"JSONPath\":\".status.phase\",\"description\":\"The current state of the MongoDB deployment.\",\"name\":\"State\",\"type\":\"string\"},{\"JSONPath\":\".spec.version\",\"description\":\"The version of MongoDB.\",\"name\":\"Version\",\"type\":\"string\"},{\"JSONPath\":\".metadata.creationTimestamp\",\"description\":\"The time since the MongoDB resource was created.\",\"name\":\"Age\",\"type\":\"date\"}],\"group\":\"mongodb.com\",\"names\":{\"kind\":\"MongoDB\",\"plural\":\"mongodb\",\"shortNames\":[\"mdb\"],\"singular\":\"mongodb\"},\"scope\":\"Namespaced\",\"subresources\":{\"status\":{}},\"validation\":{\"openAPIV3Schema\":{\"properties\":{\"spec\":{\"oneOf\":[{\"required\":[\"cloudManager\"]},{\"required\":[\"opsManager\"]},{\"required\":[\"project\"]}],\"properties\":{\"additionalMongodConfig\":{\"properties\":{\"net\":{\"properties\":{\"ssl\":{\"properties\":{\"mode\":{\"enum\":[\"disabled\",\"allowSSL\",\"preferSSL\",\"requireSSL\",\"allowTLS\",\"preferTLS\",\"requireTLS\"],\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"}},\"type\":\"object\"},\"cloudManager\":{\"properties\":{\"configMapRef\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"clusterDomain\":{\"format\":\"hostname\",\"type\":\"string\"},\"clusterName\":{\"description\":\"DEPRECATED Use clusterDomain instead\",\"format\":\"hostname\",\"type\":\"string\"},\"configServerCount\":{\"type\":\"integer\"},\"configSrvPodSpec\":{\"properties\":{\"cpu\":{\"type\":\"string\"},\"cpuRequests\":{\"type\":\"string\"},\"memory\":{\"type\":\"string\"},\"memoryRequests\":{\"type\":\"string\"},\"nodeAffinity\":{\"type\":\"object\"},\"persistence\":{\"properties\":{\"multiple\":{\"properties\":{\"data\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"journal\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"logs\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"single\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"podAffinity\":{\"type\":\"object\"},\"podAntiAffinityTopologyKey\":{\"type\":\"string\"},\"podTemplate\":{\"properties\":{\"metadata\":{\"type\":\"object\"},\"spec\":{\"type\":\"object\"}},\"type\":\"object\"}},\"type\":\"object\"},\"credentials\":{\"type\":\"string\"},\"exposedExternally\":{\"type\":\"boolean\"},\"logLevel\":{\"enum\":[\"DEBUG\",\"INFO\",\"WARN\",\"ERROR\",\"FATAL\"],\"type\":\"string\"},\"mongodsPerShardCount\":{\"type\":\"integer\"},\"mongosCount\":{\"minimum\":1,\"type\":\"integer\"},\"mongosPodSpec\":{\"properties\":{\"cpu\":{\"type\":\"string\"},\"cpuRequests\":{\"type\":\"string\"},\"memory\":{\"type\":\"string\"},\"memoryRequests\":{\"type\":\"string\"},\"nodeAffinity\":{\"type\":\"object\"},\"persistence\":{\"properties\":{\"multiple\":{\"properties\":{\"data\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"journal\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"logs\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"single\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"podAffinity\":{\"type\":\"object\"},\"podAntiAffinityTopologyKey\":{\"type\":\"string\"},\"podTemplate\":{\"properties\":{\"metadata\":{\"type\":\"object\"},\"spec\":{\"type\":\"object\"}},\"type\":\"object\"}},\"type\":\"object\"},\"opsManager\":{\"properties\":{\"configMapRef\":{\"properties\":{\"name\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"persistent\":{\"type\":\"boolean\"},\"podSpec\":{\"properties\":{\"cpu\":{\"type\":\"string\"},\"cpuRequests\":{\"type\":\"string\"},\"memory\":{\"type\":\"string\"},\"memoryRequests\":{\"type\":\"string\"},\"nodeAffinity\":{\"type\":\"object\"},\"persistence\":{\"properties\":{\"multiple\":{\"properties\":{\"data\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"journal\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"logs\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"single\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"podAffinity\":{\"type\":\"object\"},\"podAntiAffinityTopologyKey\":{\"type\":\"string\"},\"podTemplate\":{\"properties\":{\"metadata\":{\"type\":\"object\"},\"spec\":{\"type\":\"object\"}},\"type\":\"object\"}},\"type\":\"object\"},\"project\":{\"description\":\"DEPRECATED The name of a configMap in the same namespace\",\"type\":\"string\"},\"security\":{\"properties\":{\"authentication\":{\"properties\":{\"enabled\":{\"type\":\"boolean\"},\"ignoreUnknownUsers\":{\"type\":\"boolean\"},\"modes\":{\"items\":{\"enum\":[\"SCRAM\",\"X509\"],\"type\":\"string\"},\"type\":\"array\"}},\"type\":\"object\"},\"tls\":{\"properties\":{\"additionalCertificateDomains\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"},\"ca\":{\"type\":\"string\"},\"enabled\":{\"type\":\"boolean\"}},\"type\":\"object\"}},\"type\":\"object\"},\"shardCount\":{\"minimum\":1,\"type\":\"integer\"},\"shardPodSpec\":{\"properties\":{\"cpu\":{\"type\":\"string\"},\"cpuRequests\":{\"type\":\"string\"},\"memory\":{\"type\":\"string\"},\"memoryRequests\":{\"type\":\"string\"},\"nodeAffinity\":{\"type\":\"object\"},\"persistence\":{\"properties\":{\"multiple\":{\"properties\":{\"data\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"journal\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"},\"logs\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"single\":{\"properties\":{\"labelSelector\":{\"type\":\"object\"},\"storage\":{\"type\":\"string\"},\"storageClass\":{\"type\":\"string\"}},\"type\":\"object\"}},\"type\":\"object\"},\"podAffinity\":{\"type\":\"object\"},\"podAntiAffinityTopologyKey\":{\"type\":\"string\"},\"podTemplate\":{\"properties\":{\"metadata\":{\"type\":\"object\"},\"spec\":{\"type\":\"object\"}},\"type\":\"object\"}},\"type\":\"object\"},\"type\":{\"enum\":[\"Standalone\",\"ReplicaSet\",\"ShardedCluster\"],\"type\":\"string\"},\"version\":{\"pattern\":\"^[0-9]+.[0-9]+.[0-9]+(-.+)?$\",\"type\":\"string\"}},\"required\":[\"credentials\",\"type\",\"version\"],\"type\":\"object\"}},\"type\":\"object\"}},\"version\":\"v1\"}}\n"},"namespace":""},"spec":{"subresources":{"status":{}},"validation":{"openAPIV3Schema":{"oneOf":null,"properties":{"spec":{"properties":{"additionalMongodConfig":{"properties":{"net":{"properties":{"mode":null,"ssl":{"properties":{"mode":{"enum":["disabled","allowSSL","preferSSL","requireSSL","allowTLS","preferTLS","requireTLS"],"type":"string"}},"type":"object"}}},"ssl":null}},"configSrvPodSpec":{"properties":{"cpu":{"type":"string"},"cpuRequests":{"type":"string"},"memory":{"type":"string"},"memoryRequests":{"type":"string"},"nodeAffinity":{"type":"object"},"persistence":{"properties":{"multiple":{"properties":{"data":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"journal":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"logs":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"single":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"podAffinity":{"type":"object"},"podAntiAffinityTopologyKey":{"type":"string"},"podTemplate":{"properties":{"metadata":{"type":"object"},"spec":{"type":"object"}},"type":"object"},"spec":null}},"mongosPodSpec":{"properties":{"cpu":{"type":"string"},"cpuRequests":{"type":"string"},"memory":{"type":"string"},"memoryRequests":{"type":"string"},"nodeAffinity":{"type":"object"},"persistence":{"properties":{"multiple":{"properties":{"data":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"journal":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"logs":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"single":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"podAffinity":{"type":"object"},"podAntiAffinityTopologyKey":{"type":"string"},"podTemplate":{"properties":{"metadata":{"type":"object"},"spec":{"type":"object"}},"type":"object"},"spec":null}},"podSpec":{"properties":{"cpu":{"type":"string"},"cpuRequests":{"type":"string"},"memory":{"type":"string"},"memoryRequests":{"type":"string"},"nodeAffinity":{"type":"object"},"persistence":{"properties":{"multiple":{"properties":{"data":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"journal":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"logs":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"single":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"podAffinity":{"type":"object"},"podAntiAffinityTopologyKey":{"type":"string"},"podTemplate":{"properties":{"metadata":{"type":"object"},"spec":{"properties":null}}}}},"shardPodSpec":{"properties":{"cpu":{"type":"string"},"cpuRequests":{"type":"string"},"memory":{"type":"string"},"memoryRequests":{"type":"string"},"nodeAffinity":{"type":"object"},"persistence":{"properties":{"multiple":{"properties":{"data":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"journal":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"},"logs":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"single":{"properties":{"labelSelector":{"type":"object"},"storage":{"type":"string"},"storageClass":{"type":"string"}},"type":"object"}},"type":"object"},"podAffinity":{"type":"object"},"podAntiAffinityTopologyKey":{"type":"string"},"podTemplate":{"properties":{"metadata":{"type":"object"},"spec":{"type":"object"}},"type":"object"},"spec":null}}}}}}}}}
to:

but when use the branch tags/1.4.5 , it is working fine.

can you please help me to find the issue

**Comment by antonlisovenko** [comment]
Hi @Techshubh 
Thanks for your report.
What version of K8s/Openshift are you using? The issue could be the non-supported CRD syntax in older versions of K8s - in this case you should use the flag `subresourceEnabled=false` when running `helm template` or edit the CRDs manually and remove the `subresources:` section for each CRD installed

**Comment by Techshubh** [comment]
Hi,
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth SSPI Kerberos SPNEGO

Server https://cloudappsstg.necdp.com:443
openshift v3.11.161
kubernetes v1.11.0+d4cacc0


I have been able to use code tagged with 1.4.5 but latest code unable work on this version

**Comment by antonlisovenko** [comment]
Yes, Openshift 3.11 doesn't support `subresources` field in CRD so please try the recommendations above to overcome this.

**Comment by Techshubh** [comment]
Yes. it works 

Thanks
